import type { Script } from "./types";

// Guiones segundo-a-segundo (nivel principiante) de los videos del lote 1.
// Fuente: Guiones-60-Videos-Zentro.md · PARTE A refinada (2026-07-07).

export const SCRIPTS: Script[] = [
  {
    videoId: 1,
    badge: "El primero que debes PUBLICAR",
    general: {
      problem: "La vergüenza de cobrar — le pone nombre y le muestra una salida.",
      audience: "Emprendedores que fían: revendedoras, servicios, negocios familiares.",
      note: "Grabarás 3-4 minutos de material para sacar 30 s: es lo normal, no es que lo hagas mal.",
    },
    prep: {
      ropa: "Camiseta de un color sólido (azul, gris o negro).",
      fondo: "Tu escritorio real, con el monitor encendido detrás mostrando Zentro o código.",
      camara:
        "Celular vertical, fijo en el soporte (NO se mueve en todo el video), a la altura de tus ojos, a ~60 cm de tu cara.",
      plano: "Primer plano (cara y hombros). Este video es una confesión: la cercanía es a propósito.",
      recursos: [
        "Captura de un chat de WhatsApp con “Holaa, disculpa que te moleste 🙈” escrito (créala en un chat contigo mismo)",
        "Grabación de pantalla #3: el recordatorio de pago automático",
        "Clip de cortinilla (cierre con logo)",
      ],
    },
    segments: [
      {
        from: 0,
        to: 3,
        visual: "🎥 tú, primer plano",
        say: "A ti te deben dinero... y te da pena cobrarlo. Admítelo.",
        tone: "Bajo y cómplice, como contando un secreto. Pausa de 1 s después de “dinero...”",
        gesture: "Media sonrisa pícara al decir “admítelo”. Manos quietas, fuera de cuadro.",
        gaze: "Fija al lente todo el bloque.",
        edit: "Texto grande arriba: A ti también te da PENA cobrar (PENA en verde).",
      },
      {
        from: 3,
        to: 8,
        visual: "🎥 tú + 🖼️ inserto del chat 1.5 s",
        say: "Le fiaste a tu cliente “de confianza”. Ya pasó un mes. Y tú ahí... redactando el “holaa, disculpa que te moleste”.",
        tone: "Ritmo normal; en “holaa” imita el tonito meloso de quien pide perdón.",
        gesture: "Comillas con los dedos en “de confianza”; ladea la cabeza en el “holaa”.",
        gaze: "Al lente; alza los ojos al cielo en “un mes” (hartazgo).",
        edit: "Zoom de énfasis en “un mes”. Inserto del chat + SFX de teclas.",
      },
      {
        from: 8,
        to: 14,
        visual: "🎥 tú",
        say: "No eres mala para los negocios. Es que cobrar es incómodo. Para todos.",
        tone: "Serio, firme y MÁS LENTO. La frase más importante del video.",
        gesture: "Cero sonrisa. Encoge los hombros en “para todos”.",
        gaze: "Fija al lente, sin desviarla.",
        edit: "Subtítulo con “incómodo” en verde. Después: 0.5 s de silencio.",
      },
      {
        from: 14,
        to: 24,
        visual: "📱 pantalla #3 (recordatorio automático)",
        say: "Por eso hice que mi app lo haga por mí: si una factura se vence, Zentro le manda a tu cliente un recordatorio amable, con tu nombre. Él solito.",
        tone: "Voz en off de alivio; habla sonriendo (la sonrisa se oye).",
        edit: "Transición whoosh (solo sonido) al entrar. Zoom al correo en “con tu nombre”. Texto: cobra POR TI.",
      },
      {
        from: 24,
        to: 30,
        visual: "🎥 tú + cortinilla",
        say: "Yo ya no persigo a nadie. Estoy regalando 6 meses a los primeros 15 negocios que lo prueben. Comenta COBRA y te escribo.",
        tone: "Cercano, directo, un poco más rápido.",
        gesture: "Sonrisa franca; señala hacia abajo con el índice en “comenta”.",
        gaze: "Al lente.",
        edit: "Texto: comenta COBRA 👇. Música sube 1 s al final. Cortinilla 1.5 s.",
      },
    ],
    editSteps: [
      "Importa en orden: bloques 1-3 (un clip largo), grabación de pantalla #3, bloque 5, cortinilla.",
      "Limpieza (receta 0.3 paso 2): borra TODAS las pausas y errores. Debe saltar de frase a frase sin aire.",
      "Seg ~5: inserta la captura del chat como superposición de 1.5 s + SFX de teclas.",
      "La voz en off del bloque 4 va debajo del video de pantalla (toca el clip → “Extraer audio” si la grabaste como video).",
      "Zoom de énfasis en “un mes” (seg ~6) y “con tu nombre” (seg ~20).",
      "Única transición con sonido: whoosh cara→pantalla (seg 14). Lo demás, corte seco.",
      "Música “lofi tension”, volumen 15; sube a 25 en los últimos 2 s.",
      "SFX pop en cada texto grande; notificación al aparecer el correo.",
    ],
    screenTexts: [
      { layer: "titulo", text: "A ti también te da PENA cobrar", from: 0, to: 3, place: "Tercio superior", style: "Blanco, “PENA” en verde, entrada Emerger" },
      { layer: "titulo", text: "cobra POR TI", from: 18, to: 24, place: "Tercio superior", style: "Blanco, “POR TI” en verde, entrada Emerger" },
      { layer: "titulo", text: "comenta COBRA 👇", from: 26, to: 30, place: "Centro", style: "“COBRA” en verde, entrada Rebote" },
      { layer: "subtitulos", text: "Todo lo que dices, palabra por palabra", from: 0, to: "fin", place: "Centro-bajo", style: "Blanco con borde negro; en verde: pena, un mes, incómodo, 6 meses, COBRA" },
    ],
    rhythm: [
      "Rápido: bloques 2 y 5. Lento: bloque 3 (la frase seria).",
      "Silencio mirando a cámara (0.5 s) justo después de “Admítelo”.",
      "Sonríe al inicio (pícaro) y al final (franco). NO sonrías en el bloque 3.",
      "El video baja en el bloque 3 y sube en el 4-5: ese contraste ES el video.",
    ],
    mistakes: [
      "Decir “hola, soy Steve” antes del gancho: prohibido. Arrancas con “A ti te deben dinero”.",
      "Sobreactuar la pena: media sonrisa, no payasada — el tema es real para quien lo vive.",
      "Mostrar Zentro antes del segundo 14: primero el dolor, luego la solución. Al revés = anuncio = se van.",
      "Grabar la voz en off otro día o en otro cuarto: se nota el cambio de sonido. Misma sesión.",
    ],
  },
  {
    videoId: 2,
    general: {
      problem: "Le muestra al espectador POR QUÉ se siente desbordado (su negocio está regado en 6 sitios).",
      audience: "El emprendedor “desordenado-funcional”: vende bien pero vive apagando incendios.",
      note: "Este video siembra audiencia; no vende. El CTA es de comentario, no de registro.",
    },
    prep: {
      ropa: "La segunda camiseta de la sesión (distinta a la del #1, para que parezca otro día).",
      fondo: "Igual al #1 (mismo setup 0.2).",
      camara: "Fija, vertical, altura de ojos, a ~1 metro.",
      plano: "Plano medio (de la cintura para arriba): aquí usas las manos y un objeto, necesitan espacio.",
      recursos: [
        "Un cuaderno arrugado o gastado de verdad (utilería: te quita nervios)",
        "Grabación de pantalla #1: dashboard con el Centro de Prioridades",
        "Cortinilla",
      ],
    },
    segments: [
      {
        from: 0,
        to: 3,
        visual: "🎥 tú con cuaderno",
        say: "Tu negocio vive en 6 lugares. Cuéntalos conmigo.",
        tone: "Enérgico, de arranque.",
        gesture: "Cuaderno a la altura del pecho, visible. Ceja levantada, gesto de reto.",
        gaze: "Al lente.",
        edit: "Texto grande: Tu negocio vive en 6 lugares (“6” en verde).",
      },
      {
        from: 3,
        to: 13,
        visual: "🎥 tú, un corte por ítem",
        say: "Clientes: WhatsApp. Ventas: Excel. Deudas: este cuaderno. Precios: tu memoria. Facturas: una carpeta. Y las fotos de los productos... en la galería. Con las de tu perro.",
        tone: "Rápido y rítmico, un golpe por ítem. Frena en “con las de tu perro”.",
        gesture: "Cuenta con los dedos (1 a 5); agita el cuaderno en “este cuaderno”; media sonrisa en lo del perro.",
        gaze: "Al lente. Di CADA ítem como frase suelta con pausa: serán 6 cortes seguidos en edición.",
        edit: "Chips de texto acumulándose en columna izquierda + SFX pop ×6.",
      },
      {
        from: 13,
        to: 20,
        visual: "🎥 tú, serio",
        say: "Y así no se pierde plata por vender poco. Se pierde por no VER todo junto.",
        tone: "Serio, más lento, bajando el volumen un punto.",
        gesture: "Suelta el cuaderno (fuera de cuadro). Manos quietas. Sin sonrisa.",
        gaze: "Fija al lente. Tras decirlo: 0.5 s en silencio mirando a cámara.",
        edit: "Zoom en “VER”. Chips fuera de golpe. SIN música en este bloque.",
      },
      {
        from: 20,
        to: 28,
        visual: "📱 pantalla #1 + cortinilla",
        say: "Yo estoy construyendo esto: todo tu negocio en una pantalla, que cada mañana te dice qué cobrar y qué hacer primero. ¿En cuántos lugares vive el tuyo? Te leo.",
        tone: "Voz en off tranquila y curiosa; la pregunta final con invitación real.",
        edit: "3-4 s de dashboard + 3-4 s del Centro de Prioridades. Vuelve la música. Texto: ¿en cuántos vive EL TUYO?",
      },
    ],
    editSteps: [
      "Limpieza estándar. En el bloque 3-13 deja los 6 ítems como 6 cortes secos seguidos: ese salto es el ritmo.",
      "Chips acumulándose: WhatsApp / Excel / Cuaderno / Memoria / Carpeta / Galería 🐶 — columna izquierda, pop ×6.",
      "Seg 13: elimina todos los chips de golpe (pantalla limpia para la frase seria).",
      "Zoom de énfasis en “VER” (seg ~17).",
      "Seg 20: corte a pantalla #1 con voz en off debajo.",
      "Música “upbeat lofi” al 15-18. En seg 13-20: volumen 0 (el silencio hace retumbar la frase). Vuelve en seg 20.",
      "Cortinilla al final.",
    ],
    screenTexts: [
      { layer: "titulo", text: "Tu negocio vive en 6 lugares", from: 0, to: 3, place: "Tercio superior", style: "Blanco, “6” en verde, entrada Emerger" },
      { layer: "chip", text: "WhatsApp / Excel / Cuaderno / Memoria / Carpeta / Galería 🐶", from: 3, to: 13, place: "Columna, lado izquierdo", style: "Blanco, borde negro, entrada Emerger + pop (se acumulan)" },
      { layer: "titulo", text: "¿en cuántos vive EL TUYO?", from: 24, to: 28, place: "Tercio superior", style: "“EL TUYO” en verde" },
      { layer: "subtitulos", text: "Lo que dices", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: 6 lugares, plata, VER" },
    ],
    rhythm: [
      "Los seg 3-13 son los más RÁPIDOS de todos tus videos: 6 golpes en 10 segundos.",
      "El frenazo del seg 13 (serio, lento, sin música) es el momento clave.",
      "Sonríe SOLO en el remate del perro y en la pregunta final.",
    ],
    mistakes: [
      "Decir los 6 lugares de corrido en una sola toma: pierde el ritmo. Son 6 frases separadas.",
      "Chips en lugares distintos cada vez: van ordenados en columna, mismo lado.",
      "Olvidar quitar la música en la frase seria: el silencio es parte del guion.",
      "Alargar la parte de pantalla más de 8 s: es una siembra, no un demo.",
    ],
  },
  {
    videoId: 4,
    badge: "Para FIJAR en los 3 perfiles",
    general: {
      problem: "El interesado necesita entender la oferta completa en 35 s, en un solo lugar.",
      audience: "El emprendedor que ya te vio 1-2 veces y está evaluando si entrar.",
      note: "“Fijar” = en tu perfil, opción “Fijar” sobre el video publicado; queda siempre de primero. Hazlo en TikTok, IG y FB apenas lo subas.",
    },
    prep: {
      ropa: "Tu mejor camiseta lisa (es tu carta de presentación permanente).",
      fondo: "Escritorio con Zentro visible en el monitor detrás — aquí importa más que nunca.",
      camara: "Fija, vertical, altura de ojos, a ~80 cm.",
      plano: "Entre primer plano y plano medio (cara, hombros y espacio para contar con los dedos).",
      recursos: ["Grabación de pantalla #9: scroll general de la app", "Cortinilla"],
    },
    segments: [
      {
        from: 0,
        to: 3,
        visual: "🎥 tú",
        say: "Busco 15 negocios. Y no, no les voy a cobrar. Es al revés.",
        tone: "Directo, seguro, sin prisa.",
        gesture: "Manos abiertas y activas. Leve sonrisa en “es al revés”.",
        gaze: "Al lente, firme.",
        edit: "Texto: busco 15 negocios (“15” en verde).",
      },
      {
        from: 3,
        to: 12,
        visual: "🎥 tú + 📱 flash de 2 s en “ya funciona”",
        say: "Construí Zentro: una app que junta tu negocio en un solo lugar... y hasta les cobra a tus clientes por ti. Ya funciona. Pero antes de abrirla al mundo, necesito 15 negocios reales que la usen y me digan qué mejorar.",
        tone: "Orgullo tranquilo (no vendedor). Micro-pausa antes de “ya funciona”.",
        gesture: "Asiente ligeramente en “ya funciona”.",
        gaze: "Al lente.",
        edit: "Superposición de pantalla #9 (2 s) en “ya funciona”. “reales” en verde en el subtítulo.",
      },
      {
        from: 12,
        to: 24,
        visual: "🎥 tú contando con dedos",
        say: "A cambio: Pro gratis 6 meses. Precio de fundador para siempre. Mi WhatsApp personal. Y lo que yo programe... sale de lo que TÚ me pidas.",
        tone: "Rítmico: un golpe por beneficio (4 frases sueltas).",
        gesture: "Cuenta 1-2-3-4 con los dedos. En “TÚ me pidas”: inclínate 10 cm hacia la cámara.",
        gaze: "Al lente.",
        edit: "Chips con ✓ verde acumulándose (pop ×4). Zoom en “TÚ me pidas”.",
      },
      {
        from: 24,
        to: 30,
        visual: "🎥 tú",
        say: "¿Por qué solo 15? Porque a cada uno lo acompaño yo, personalmente. Y mi día tiene las mismas horas que el tuyo.",
        tone: "Honesto, bajando el ritmo, media sonrisa al final.",
        gesture: "Encoge los hombros en la última frase (“así es la cosa”).",
        gaze: "Al lente.",
        edit: "Texto: solo 15 · onboarding personal. Micro-silencio tras “¿Por qué solo 15?”.",
      },
      {
        from: 30,
        to: 35,
        visual: "🎥 tú + cortinilla",
        say: "Si llevas tu negocio en WhatsApp, Excel o un cuaderno: comenta FUNDADOR y te escribo hoy.",
        tone: "Cierre directo y cálido.",
        gesture: "Señala abajo con el índice en “comenta”. Sonrisa franca final.",
        gaze: "Al lente.",
        edit: "Texto: comenta FUNDADOR 👇. Cortinilla.",
      },
    ],
    editSteps: [
      "Limpieza un pelín MENOS agresiva que en #1-#2: este video puede respirar (calma = seguridad).",
      "Seg ~8: 2 s de pantalla #9 a pantalla completa y de vuelta a ti.",
      "Chips de beneficios: “✓ Pro gratis 6 meses” / “✓ Precio de fundador PARA SIEMPRE” / “✓ Mi WhatsApp directo” / “✓ Tu voz define el producto”.",
      "Zoom en “TÚ me pidas” (se suma a tu inclinación física: doble énfasis).",
      "Sin transiciones de sonido: todo corte seco (más sobrio = más creíble).",
      "Música “inspiring minimal” o piano suave, volumen 12-15 (más baja que en los otros).",
      "Cortinilla al final.",
    ],
    screenTexts: [
      { layer: "titulo", text: "busco 15 negocios (y no les voy a cobrar)", from: 0, to: 3, place: "Tercio superior", style: "“15” en verde, entrada Emerger" },
      { layer: "chip", text: "✓ Pro gratis 6 meses / ✓ Precio para siempre / ✓ Mi WhatsApp / ✓ Tu voz define", from: 12, to: 24, place: "Columna izquierda", style: "✓ verde, texto blanco" },
      { layer: "titulo", text: "solo 15 · onboarding personal", from: 24, to: 30, place: "Tercio superior", style: "“15” verde" },
      { layer: "titulo", text: "comenta FUNDADOR 👇", from: 31, to: 35, place: "Centro", style: "“FUNDADOR” verde, entrada Rebote" },
      { layer: "subtitulos", text: "Lo que dices", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: 15, gratis, para siempre, TÚ, FUNDADOR" },
    ],
    rhythm: [
      "Tu video más CALMADO: seguridad > velocidad. Sin gritos, sin hype.",
      "Micro-silencio (0.5 s) después de “es al revés” y de “¿Por qué solo 15?”.",
      "Sonríe en “es al revés”, en “las mismas horas que el tuyo” y al final. El resto: gesto neutro-seguro.",
    ],
    mistakes: [
      "Sonar a vendedor de TV (“¡¡aprovecha YA!!”): la oferta es fuerte por sí sola; dila como un hecho.",
      "Listar los beneficios de corrido sin pausas: son 4 frases separadas, con su chip cada una.",
      "No fijarlo en los perfiles tras publicarlo: fijarlo es la mitad del valor de este video.",
      "Regrabarlo 20 veces buscando perfección: “seguro y natural” le gana a “perfecto y tieso”.",
    ],
  },
  {
    videoId: 5,
    badge: "El primero que debes GRABAR",
    general: {
      problem: "El espectador no imagina cómo se ve “tener el negocio bajo control”; este video se lo hace sentir.",
      audience: "Cualquier emprendedor; en especial quien ya vio un video de dolor tuyo.",
      note: "Por qué grabarlo primero: es 90% grabación de pantalla + tu voz leyendo tranquilo. Solo 1.5 s de tu cara al final. Cero presión: perfecto para soltarte.",
    },
    prep: {
      ropa: "La que sea (solo sales 1.5 s al final; para ese clip, camiseta lisa).",
      fondo: "Para el clip final: tu escritorio de siempre.",
      camara: "La protagonista es la grabadora de pantalla del teléfono (menú rápido → Grabar pantalla).",
      plano: "Clip final: primer plano (60 cm), sonrisa tranquila, UNA frase.",
      recursos: [
        "Grabación de pantalla #1 (dashboard + prioridades) hecha LENTO y con el dedo firme",
        "Grabación de pantalla #6 (quién te debe)",
        "Voz en off grabada con audífonos-micrófono (aquí SÍ puedes leer el guion: no se te ve)",
        "Clip de tu cara 1.5 s + cortinilla",
      ],
    },
    segments: [
      {
        from: 0,
        to: 3,
        visual: "📱 dedo abriendo Zentro → dashboard",
        say: "Son las 7 de la mañana. Abro la app de mi negocio...",
        tone: "Voz en off tranquila, como pensando en voz alta.",
        edit: "Texto: POV: tu negocio te dice qué hacer HOY. SFX notificación suave. Música lo-fi al 18 desde el seg 0.",
      },
      {
        from: 3,
        to: 10,
        visual: "📱 Centro de Prioridades",
        say: "...y ya sé exactamente qué hacer hoy: cobrarle a Marta la factura vencida, confirmar el pedido de Luis... y esta semana entran 340 dólares.",
        tone: "Serena, sin prisa.",
        edit: "3 zooms suaves (105-110%), uno por ítem al nombrarlo. Cifra en verde en el subtítulo. SFX pop ×3.",
      },
      {
        from: 10,
        to: 17,
        visual: "📱 2 s por “quién te debe” y vuelve",
        say: "No lo pensé yo. No revisé seis aplicaciones. La app lo calculó sola, con mis ventas y mis facturas.",
        tone: "Igual de serena.",
        edit: "Corte seco entre pantallas. Aquí NO hay zooms: deja respirar.",
      },
      {
        from: 17,
        to: 22,
        visual: "🎥 TU CARA por primera vez (1.5 s) + cortinilla",
        say: "Así se siente tener el control. Es gratis: link en bio.",
        tone: "Sonrisa tranquila, no eufórica.",
        gaze: "Al lente.",
        edit: "La aparición de tu cara ES la sorpresa del video. Texto: gratis · link en bio (“gratis” en verde).",
      },
    ],
    editSteps: [
      "Línea de tiempo: pantalla #1 → #6 → tu clip de cara → cortinilla. La voz en off debajo de todo.",
      "Recorta la pantalla para que cada cosa nombrada aparezca JUSTO cuando la nombras (prueba y error, 10 min).",
      "3 zooms suaves con keyframes en el seg 3-10, uno por ítem.",
      "Música lo-fi al 18; bájala a 12 si compite con tu voz.",
      "Subtítulos automáticos sobre la voz en off, como siempre.",
    ],
    screenTexts: [
      { layer: "titulo", text: "POV: tu negocio te dice qué hacer HOY", from: 0, to: 5, place: "Tercio superior", style: "“HOY” en verde, entrada Emerger" },
      { layer: "titulo", text: "gratis · link en bio", from: 18, to: 22, place: "Centro", style: "“gratis” en verde" },
      { layer: "subtitulos", text: "La voz en off completa", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: qué hacer hoy, 340, sola, gratis" },
    ],
    rhythm: [
      "TODO el video es lento y sereno — el único así del lote, a propósito: vende CALMA.",
      "La única “subida” es tu cara al final: sonrisa tranquila.",
    ],
    mistakes: [
      "Mover el dedo rápido en la grabación de pantalla: el espectador se pierde. Lento y deliberado.",
      "Poner música movida: mata la sensación de control. Lo-fi suave o piano.",
      "Saltarte el clip de tu cara “porque da pena”: esos 1.5 s convierten un screencast en un video de fundador.",
      "Inventar datos exagerados: usa los del usuario de prueba, creíbles ($340, no $50.000).",
    ],
  },
];

export function getScript(videoId: number): Script | undefined {
  return SCRIPTS.find((s) => s.videoId === videoId);
}
