import type { Script } from "./types";

// Guiones segundo-a-segundo con dirección de grabación completa (v2, 2026-07-08).
// Cada bloque indica: qué decir, tono, energía, cuerpo, cámara, mirada, manos y edición.
// Regla general de grabación: cada fila es un BLOQUE que dices por separado, con pausa
// de 2 s entre bloques. Los errores se repiten sin cortar; se limpian en edición.

export const SCRIPTS: Script[] = [
  // ============================================================ #1
  {
    videoId: 1,
    badge: "El primero que debes PUBLICAR",
    general: {
      problem: "La vergüenza de cobrar — le pone nombre y le muestra una salida.",
      audience: "Emprendedores que fían: revendedoras, servicios, negocios familiares.",
      note: "Grabarás 3-4 minutos de material para sacar 30 s: es lo normal, no es que lo hagas mal.",
    },
    prep: {
      ropa: "Camiseta de un color sólido (azul, gris o negro).",
      fondo: "Tu escritorio real, con el monitor encendido detrás mostrando Zentro o código.",
      camara: "Celular vertical, FIJO en el soporte todo el video, a la altura exacta de tus ojos, a ~60 cm (un brazo estirado).",
      plano: "Primer plano (cara y hombros). Es una confesión: la cercanía es a propósito.",
      recursos: [
        "Captura de un chat de WhatsApp con “Holaa, disculpa que te moleste 🙈” escrito (créala en un chat contigo mismo)",
        "Grabación de pantalla #3: el recordatorio de pago automático",
        "Clip de cortinilla (cierre con logo)",
      ],
    },
    segments: [
      {
        from: 0, to: 3, visual: "Tú, primer plano",
        say: "A ti te deben dinero... y te da pena cobrarlo. Admítelo.",
        tone: "Bajo y cómplice, como contando un secreto. Pausa de 1 s después de “dinero...”.",
        energy: "Baja y contenida (40%): el susurro detiene el scroll más que el grito.",
        body: "Sentado, espalda recta, inclinado 5° hacia la cámara, hombros relajados.",
        camera: "Fija, primer plano, a la altura de tus ojos. No la toques.",
        gesture: "Media sonrisa pícara SOLO al decir “admítelo”. Manos quietas, fuera de cuadro.",
        gaze: "Fija al lente TODO el bloque, sin parpadear de más.",
        edit: "Texto grande arriba desde el frame 1: A ti también te da PENA cobrar (PENA en verde). SIN música aún.",
      },
      {
        from: 3, to: 8, visual: "Tú + inserto del chat 1.5 s",
        say: "Le fiaste a tu cliente “de confianza”. Ya pasó un mes. Y tú ahí... redactando el “holaa, disculpa que te moleste”.",
        tone: "Ritmo conversacional; en “holaa” imita el tonito meloso de quien pide perdón.",
        energy: "Media (60%), subiendo: estás contando el chisme.",
        body: "Misma postura; ladea la cabeza 15° en el “holaa”.",
        camera: "Fija. El “movimiento” lo pone la edición (zoom en “un mes”).",
        gesture: "Comillas con los dedos en “de confianza” (manos entran al cuadro solo ahí).",
        gaze: "Al lente; alza los ojos al cielo medio segundo en “un mes” (hartazgo) y regresa.",
        edit: "Zoom de énfasis 110% en “un mes” (0.2 s). Inserto del chat en seg 5-6.5 a pantalla completa + SFX de teclas. Entra música “lofi tension” al 15.",
      },
      {
        from: 8, to: 14, visual: "Tú",
        say: "No eres mala para los negocios. Es que cobrar es incómodo. Para todos.",
        tone: "Serio, firme y MÁS LENTO: separa las tres frases con medio segundo.",
        energy: "Baja a 30%: este es el frenazo del video. Volumen un punto menos.",
        body: "Quieto total. Sin ladear la cabeza. Hombros caen ligeramente en “para todos”.",
        camera: "Fija. Nada de zoom aquí: la quietud ES el énfasis.",
        gesture: "Cero sonrisa. Encogimiento de hombros lento en “para todos”.",
        gaze: "Clavada al lente sin desviarla ni un frame. Tras la última palabra: 0.5 s de silencio mirando.",
        edit: "Subtítulo con “incómodo” en verde. Música baja a volumen 8 durante este bloque y vuelve a 15 al salir.",
      },
      {
        from: 14, to: 24, visual: "Pantalla #3 (recordatorio automático)",
        say: "Por eso hice que mi app lo haga por mí: si una factura se vence, Zentro le manda a tu cliente un recordatorio amable, con tu nombre. Él solito.",
        tone: "Voz en off de alivio; habla sonriendo (la sonrisa se OYE aunque no se vea).",
        energy: "Media-alta (70%): es la buena noticia.",
        camera: "No sales tú. La grabación de pantalla va LENTA; el dedo señala el correo.",
        edit: "Transición: SOLO el sonido whoosh al entrar (corte seco visual). Zoom 108% al correo en “con tu nombre” y mantener 1 s. Texto: cobra POR TI. SFX notificación al aparecer el correo.",
      },
      {
        from: 24, to: 30, visual: "Tú + cortinilla",
        say: "Yo ya no persigo a nadie. Estoy regalando 6 meses a los primeros 15 negocios que lo prueben. Comenta COBRA y te escribo.",
        tone: "Cercano y directo, un 10% más rápido que el bloque 2.",
        energy: "Alta (80%): cierre con impulso, sin gritar.",
        body: "Inclínate 5 cm más hacia la cámara al empezar el bloque (cercanía física = urgencia amable).",
        camera: "Fija, primer plano.",
        gesture: "Sonrisa franca sostenida; el índice señala hacia abajo EXACTAMENTE al decir “comenta”.",
        gaze: "Al lente hasta el último frame; no mires el botón de stop al terminar (deja 2 s de aire grabando).",
        edit: "Texto: comenta COBRA 👇 (COBRA en verde, entrada rebote). Música sube a 25 el último segundo. Cortinilla 1.5 s.",
      },
    ],
    editSteps: [
      "Importa en orden: bloques 1-3 (un clip largo), grabación de pantalla #3, bloque 5, cortinilla.",
      "Limpieza: borra TODAS las pausas y errores. Debe saltar de frase a frase sin aire (receta del Manual, paso 2).",
      "Seg ~5: captura del chat como superposición de 1.5 s + SFX de teclas.",
      "Voz en off del bloque 4 debajo del video de pantalla (clip → “Extraer audio” si la grabaste como video).",
      "Zooms de énfasis: “un mes” (seg ~6) y “con tu nombre” (seg ~20). Nada más.",
      "Única transición con sonido: whoosh cara→pantalla (seg 14). Lo demás, corte seco.",
      "Música “lofi tension”: entra en seg 3 al 15, baja a 8 en seg 8-14, sube a 25 el último segundo.",
      "SFX: pop en cada texto grande, teclas en el inserto, notificación en el correo.",
    ],
    screenTexts: [
      { layer: "titulo", text: "A ti también te da PENA cobrar", from: 0, to: 3, place: "Tercio superior", style: "Blanco, “PENA” en verde, entrada Emerger" },
      { layer: "titulo", text: "cobra POR TI", from: 18, to: 24, place: "Tercio superior", style: "Blanco, “POR TI” en verde, entrada Emerger" },
      { layer: "titulo", text: "comenta COBRA 👇", from: 26, to: 30, place: "Centro", style: "“COBRA” en verde, entrada Rebote" },
      { layer: "subtitulos", text: "Todo lo que dices, palabra por palabra", from: 0, to: "fin", place: "Centro-bajo", style: "Blanco con borde negro; en verde: pena, un mes, incómodo, 6 meses, COBRA" },
    ],
    rhythm: [
      "Arco de energía: 40% → 60% → 30% (frenazo) → 70% → 80%. El contraste del bloque 3 ES el video.",
      "Silencio mirando a cámara (0.5 s) justo después de “Admítelo” y de “Para todos”.",
      "Sonríe al inicio (pícaro) y al final (franco). PROHIBIDO sonreír en el bloque 3.",
    ],
    mistakes: [
      "Decir “hola, soy Steve” antes del gancho: prohibido. Arrancas con “A ti te deben dinero”.",
      "Sobreactuar la pena: media sonrisa, no payasada — el tema es real para quien lo vive.",
      "Mostrar Zentro antes del segundo 14: primero el dolor, luego la solución. Al revés = anuncio = se van.",
      "Grabar la voz en off otro día o en otro cuarto: se nota el cambio de sonido. Misma sesión.",
    ],
  },

  // ============================================================ #2
  {
    videoId: 2,
    general: {
      problem: "Le muestra al espectador POR QUÉ se siente desbordado (su negocio está regado en 6 sitios).",
      audience: "El emprendedor “desordenado-funcional”: vende bien pero vive apagando incendios.",
      note: "Este video siembra audiencia; no vende. El CTA es de comentario, no de registro.",
    },
    prep: {
      ropa: "La segunda camiseta de la sesión (distinta a la del #1: parece otro día).",
      fondo: "Igual al #1 (mismo setup del Manual).",
      camara: "Fija, vertical, altura de ojos, a ~1 metro.",
      plano: "Plano medio (cintura para arriba): usarás las manos y un objeto, necesitan espacio en el cuadro.",
      recursos: [
        "Un cuaderno arrugado o gastado de verdad (utilería: te quita nervios)",
        "Grabación de pantalla #1: dashboard con el Centro de Prioridades",
        "Cortinilla",
      ],
    },
    segments: [
      {
        from: 0, to: 3, visual: "Tú con cuaderno",
        say: "Tu negocio vive en 6 lugares. Cuéntalos conmigo.",
        tone: "De arranque, retador y amistoso.",
        energy: "Alta desde el frame 1 (75%): este video abre con impulso, no con susurro.",
        body: "Sentado, torso erguido, cuaderno sostenido a la altura del pecho con la mano izquierda.",
        camera: "Fija, plano medio. Verifica que el cuaderno entre completo en el cuadro.",
        gesture: "Ceja levantada, gesto de reto. El cuaderno visible pero quieto.",
        gaze: "Al lente.",
        edit: "Texto grande: Tu negocio vive en 6 lugares (“6” en verde). Música “upbeat lofi” al 18 desde el inicio.",
      },
      {
        from: 3, to: 13, visual: "Tú, un corte por ítem",
        say: "Clientes: WhatsApp. Ventas: Excel. Deudas: este cuaderno. Precios: tu memoria. Facturas: una carpeta. Y las fotos de los productos... en la galería. Con las de tu perro.",
        tone: "Rítmico, un golpe por ítem. FRENA y baja el tono en “con las de tu perro”.",
        energy: "Alta (80%) y constante; cada ítem es una frase SUELTA con su pausa (serán 6 cortes).",
        body: "El torso gira 5° hacia un lado distinto en cada ítem (variedad visual sin mover la cámara).",
        camera: "Fija. Los 6 cortes de edición hacen el movimiento.",
        gesture: "Cuenta con los dedos 1-5; agita el cuaderno frente a la cámara en “este cuaderno”; media sonrisa en lo del perro.",
        gaze: "Al lente en cada ítem.",
        edit: "6 cortes secos seguidos. Chips de texto acumulándose en columna izquierda (SFX pop ×6): WhatsApp / Excel / Cuaderno / Memoria / Carpeta / Galería 🐶.",
      },
      {
        from: 13, to: 20, visual: "Tú, serio",
        say: "Y así no se pierde plata por vender poco. Se pierde por no VER todo junto.",
        tone: "Serio, lento, un punto más bajo de volumen.",
        energy: "Frenazo a 30%. El contraste con el bloque anterior es el momento clave del video.",
        body: "Suelta el cuaderno FUERA de cuadro antes de hablar. Manos quietas sobre la mesa o fuera del cuadro.",
        camera: "Fija. Sin zoom hasta la palabra “VER”.",
        gesture: "Sin sonrisa. Rostro neutro-firme.",
        gaze: "Clavada al lente. Tras decirlo: 0.5 s de silencio mirando a cámara (respiro dramático).",
        edit: "Chips fuera DE GOLPE al entrar este bloque (pantalla limpia). Zoom 110% en “VER”. MÚSICA A CERO todo el bloque.",
      },
      {
        from: 20, to: 28, visual: "Pantalla #1 + cortinilla",
        say: "Yo estoy construyendo esto: todo tu negocio en una pantalla, que cada mañana te dice qué cobrar y qué hacer primero. ¿En cuántos lugares vive el tuyo? Te leo.",
        tone: "Voz en off tranquila y curiosa; la pregunta final con invitación real, no retórica.",
        energy: "Media (55%), en calma: la solución se muestra, no se grita.",
        camera: "Grabación de pantalla lenta: 3-4 s de dashboard + 3-4 s del Centro de Prioridades.",
        edit: "Corte seco a pantalla. Vuelve la música al 18. Texto: ¿en cuántos vive EL TUYO? Cortinilla al final.",
      },
    ],
    editSteps: [
      "Limpieza estándar. En el bloque 3-13 deja los 6 ítems como 6 cortes secos seguidos: ese salto es el ritmo.",
      "Chips acumulándose en columna izquierda, pop ×6; TODOS fuera de golpe en seg 13.",
      "Zoom de énfasis en “VER” (seg ~17).",
      "Seg 20: corte a pantalla #1 con voz en off debajo.",
      "Música “upbeat lofi” 18 → 0 (seg 13-20) → 18. El silencio hace retumbar la frase seria.",
      "Cortinilla al final.",
    ],
    screenTexts: [
      { layer: "titulo", text: "Tu negocio vive en 6 lugares", from: 0, to: 3, place: "Tercio superior", style: "Blanco, “6” en verde, entrada Emerger" },
      { layer: "chip", text: "WhatsApp / Excel / Cuaderno / Memoria / Carpeta / Galería 🐶", from: 3, to: 13, place: "Columna, lado izquierdo", style: "Blanco, borde negro, entrada Emerger + pop (se acumulan)" },
      { layer: "titulo", text: "¿en cuántos vive EL TUYO?", from: 24, to: 28, place: "Tercio superior", style: "“EL TUYO” en verde" },
      { layer: "subtitulos", text: "Lo que dices", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: 6 lugares, plata, VER" },
    ],
    rhythm: [
      "Los seg 3-13 son los más RÁPIDOS de todos tus videos: 6 golpes en 10 segundos.",
      "El frenazo del seg 13 (serio + lento + sin música) es el momento clave.",
      "Sonríe SOLO en el remate del perro y en la pregunta final.",
    ],
    mistakes: [
      "Decir los 6 lugares de corrido en una sola toma: pierde el ritmo. Son 6 frases separadas.",
      "Chips en lugares distintos cada vez: van ordenados en columna, mismo lado.",
      "Olvidar quitar la música en la frase seria: el silencio es parte del guion.",
      "Alargar la parte de pantalla más de 8 s: es una siembra, no un demo.",
    ],
  },

  // ============================================================ #3
  {
    videoId: 3,
    badge: "Fijar en IG junto al #4",
    general: {
      problem: "Nadie confía sus números a un desconocido: esta es la historia que te vuelve alguien.",
      audience: "Quien acaba de descubrirte y visita tu perfil para decidir si te sigue.",
      note: "Único video de 45 s del lote: el storytelling justifica la excepción de duración.",
    },
    prep: {
      ropa: "Camiseta lisa oscura (la historia pide sobriedad).",
      fondo: "Escritorio con el monitor mostrando CÓDIGO (no la app): refuerza “lo estoy construyendo”.",
      camara: "Fija, vertical, altura de ojos, a ~80 cm.",
      plano: "Entre primer plano y plano medio: íntimo pero con aire para gestos.",
      recursos: [
        "3 insertos de 1 s: cuaderno con números, pantalla de Excel, chats de WhatsApp",
        "Grabación de pantalla #1 (Centro de Prioridades)",
        "Música de piano emotivo (biblioteca CapCut, buscar “emotional piano”)",
        "Cortinilla",
      ],
    },
    segments: [
      {
        from: 0, to: 4, visual: "Tú",
        say: "Pude hacer una app de facturas más. Dije que no.",
        tone: "Sereno y firme, como quien empieza una historia importante.",
        energy: "Media-baja (45%): la calma da peso.",
        body: "Sentado, quieto, manos entrelazadas fuera de cuadro o sobre la mesa.",
        camera: "Fija. Este video casi no tiene zooms: la historia sostiene sola.",
        gesture: "Niega lentamente con la cabeza en “dije que no”.",
        gaze: "Al lente.",
        edit: "Texto: renuncié a hacerla FÁCIL (FÁCIL en verde). Piano al 12 desde el inicio.",
      },
      {
        from: 4, to: 16, visual: "Tú + 3 insertos de 1 s",
        say: "Todos los emprendedores que conozco tienen el mismo problema: venden, se esfuerzan... y aún así no saben si están ganando. Tienen MIL datos: WhatsApp, Excel, cuadernos. Y CERO respuestas.",
        tone: "Narrativo, construyendo el problema. Acentúa “MIL” y “CERO”.",
        energy: "Sube gradual de 45% a 65%.",
        body: "Inclínate 5 cm adelante en “el mismo problema” y quédate ahí.",
        camera: "Fija; los insertos ponen el movimiento.",
        gesture: "Mano derecha marca “MIL” (dedos abiertos) y “CERO” (puño cerrado).",
        gaze: "Al lente; puedes mirar 1 s hacia los insertos imaginarios (arriba-izquierda) al nombrar WhatsApp/Excel/cuadernos, y volver.",
        edit: "Insertos de 1 s: cuaderno (seg 10), Excel (seg 11), chats (seg 12). Corte cada 3 s. [MIL] y [CERO] en verde en el subtítulo.",
      },
      {
        from: 16, to: 30, visual: "Tú → pantalla #1",
        say: "Las apps que existen guardan datos. Ninguna te dice qué HACER con ellos. Entonces me obsesioné con una pregunta: ¿y si tu negocio te dijera cada mañana “hoy cobra esto, haz esto primero”?",
        tone: "El punto de giro: sube la intención, como compartiendo el hallazgo.",
        energy: "70%. La pregunta final se dice LENTA y clara.",
        body: "Al hacer la pregunta, abre las palmas hacia arriba (gesto de ofrecer).",
        camera: "Fija hasta seg 24; ahí corte a pantalla #1 mostrando prioridades del día.",
        gesture: "Zoom de edición en “qué HACER”, tú no te mueves.",
        gaze: "Al lente; parpadeo natural, sin mirar el guion.",
        edit: "Zoom 110% en “qué HACER”. En seg 24 corte a pantalla (la respuesta a la pregunta SE VE). SFX pop suave.",
      },
      {
        from: 30, to: 40, visual: "Pantalla → tú",
        say: "Así nació Zentro. Z de centro: el centro de control de tu negocio. Llevo meses construyéndolo, y esta serie es la historia en vivo.",
        tone: "Orgullo tranquilo. “Z de centro” se dice despacio (es la marca).",
        energy: "65%, estable.",
        body: "De vuelta a ti: misma postura, media sonrisa serena.",
        camera: "Corte seco pantalla→tú en “Así nació Zentro”.",
        gaze: "Al lente.",
        edit: "Texto: el CENTRO de control de tu negocio (CENTRO en verde). Piano sube al 18.",
      },
      {
        from: 40, to: 45, visual: "Tú + cortinilla",
        say: "Sígueme para ver cómo termina. O mejor: para ser parte.",
        tone: "Invitación personal, sin súplica.",
        energy: "60%, cálido.",
        gesture: "Sonrisa franca en “para ser parte”.",
        gaze: "Al lente hasta el final.",
        edit: "Texto: sígueme · esta historia continúa. Cortinilla.",
      },
    ],
    editSteps: [
      "Este video se edita DIFERENTE: cortes cada 3 s (no cada 2), un solo zoom, piano constante — es una historia, no un anuncio.",
      "Insertos de 1 s en seg 10-12: cuaderno, Excel, chats.",
      "Corte a pantalla #1 exactamente cuando terminas la pregunta (seg 24): la app ES la respuesta.",
      "Piano: 12 → 18 (seg 30) → fade out con la cortinilla.",
      "Subtítulos completos; verde en: MIL, CERO, qué HACER, CENTRO.",
    ],
    screenTexts: [
      { layer: "titulo", text: "renuncié a hacerla FÁCIL", from: 0, to: 4, place: "Tercio superior", style: "“FÁCIL” en verde, entrada Emerger" },
      { layer: "titulo", text: "el CENTRO de control de tu negocio", from: 32, to: 40, place: "Tercio superior", style: "“CENTRO” en verde" },
      { layer: "titulo", text: "sígueme · esta historia continúa", from: 41, to: 45, place: "Centro", style: "Blanco, entrada Emerger" },
      { layer: "subtitulos", text: "Todo el relato", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: MIL, CERO, qué HACER, CENTRO" },
    ],
    rhythm: [
      "Arco: calma (45%) → problema creciendo (65%) → hallazgo (70%) → orgullo (65%) → invitación (60%).",
      "Pausa de 1 s ANTES de la pregunta clave (“¿y si tu negocio...?”): anúnciala con silencio.",
      "Este video NO tiene frenazos bruscos: fluye como historia contada a un amigo.",
    ],
    mistakes: [
      "Contarlo como pitch de negocio: es una historia personal. Si suena a inversor, regrábalo.",
      "Acelerar la pregunta central: es EL momento; dila lenta y clara.",
      "Meter más de 3 insertos: saturan una narración que vive de tu cara.",
      "Olvidar fijarlo en IG junto al #4 cuando lo publiques.",
    ],
  },

  // ============================================================ #4
  {
    videoId: 4,
    badge: "Para FIJAR en los 3 perfiles",
    general: {
      problem: "El interesado necesita la oferta completa, clara, en 35 segundos, en un solo lugar.",
      audience: "El emprendedor que ya te vio 1-2 veces y está evaluando si entrar.",
      note: "“Fijar” = opción “Fijar” sobre el video publicado en tu perfil; queda siempre de primero. Hazlo en TikTok, IG y FB apenas lo subas.",
    },
    prep: {
      ropa: "Tu mejor camiseta lisa (es tu carta de presentación permanente).",
      fondo: "Escritorio con Zentro visible en el monitor detrás — aquí importa más que nunca.",
      camara: "Fija, vertical, altura de ojos, a ~80 cm.",
      plano: "Entre primer plano y plano medio (cara, hombros y espacio para contar con los dedos).",
      recursos: ["Grabación de pantalla #9: scroll general de la app", "Cortinilla"],
    },
    segments: [
      {
        from: 0, to: 3, visual: "Tú",
        say: "Busco 15 negocios. Y no, no les voy a cobrar. Es al revés.",
        tone: "Directo, seguro, sin prisa. Micro-pausa antes de “es al revés”.",
        energy: "Media (60%) y estable: la seguridad no grita.",
        body: "Sentado, espalda recta, hombros abiertos, quieto.",
        camera: "Fija todo el video. Cero movimientos: sobriedad = credibilidad.",
        gesture: "Manos abiertas visibles. Leve sonrisa SOLO en “es al revés”.",
        gaze: "Al lente, firme, sin parpadear de más.",
        edit: "Texto: busco 15 negocios (“15” en verde). Música “inspiring minimal” al 12.",
      },
      {
        from: 3, to: 12, visual: "Tú + flash de pantalla 2 s",
        say: "Construí Zentro: una app que junta tu negocio en un solo lugar... y hasta les cobra a tus clientes por ti. Ya funciona. Pero antes de abrirla al mundo, necesito 15 negocios reales que la usen y me digan qué mejorar.",
        tone: "Orgullo tranquilo (no vendedor). Micro-pausa antes de “ya funciona”.",
        energy: "60%, constante.",
        body: "Asiente ligeramente (2 cm) en “ya funciona”.",
        camera: "Fija; superposición de pantalla #9 (2 s) exactamente en “ya funciona”.",
        gesture: "Manos tranquilas; una palma se abre hacia la cámara en “te digan qué mejorar”.",
        gaze: "Al lente.",
        edit: "Pantalla #9 a pantalla completa 2 s y de vuelta. “reales” en verde en el subtítulo.",
      },
      {
        from: 12, to: 24, visual: "Tú contando con dedos",
        say: "A cambio: Pro gratis 6 meses. Precio de fundador para siempre. Mi WhatsApp personal. Y lo que yo programe... sale de lo que TÚ me pidas.",
        tone: "Rítmico: 4 frases sueltas, un golpe cada una, pausa entre ellas.",
        energy: "Sube a 70%: es la parte generosa.",
        body: "En “TÚ me pidas”: inclínate 10 cm hacia la cámara y sostén 1 s (el énfasis físico más fuerte que existe).",
        camera: "Fija; el zoom de edición acompaña tu inclinación en “TÚ”.",
        gesture: "Cuenta 1-2-3-4 con los dedos, mano a la altura del pecho, dentro del cuadro.",
        gaze: "Al lente; en “TÚ me pidas” la mirada se intensifica (ceja baja levemente).",
        edit: "Chips con ✓ verde acumulándose (pop ×4). Zoom 108% en “TÚ me pidas” sumado a tu inclinación: doble énfasis.",
      },
      {
        from: 24, to: 30, visual: "Tú",
        say: "¿Por qué solo 15? Porque a cada uno lo acompaño yo, personalmente. Y mi día tiene las mismas horas que el tuyo.",
        tone: "Honesto, bajando el ritmo. Media sonrisa al final.",
        energy: "Baja a 50%: la honestidad se dice despacio.",
        body: "Vuelve a la postura recta. Encoge los hombros lento en la última frase (“así es la cosa”).",
        camera: "Fija.",
        gesture: "Manos quietas.",
        gaze: "Al lente; después de “¿Por qué solo 15?” medio segundo de silencio mirando (deja flotar la pregunta).",
        edit: "Texto: solo 15 · onboarding personal (“15” verde). Sin zoom.",
      },
      {
        from: 30, to: 35, visual: "Tú + cortinilla",
        say: "Si llevas tu negocio en WhatsApp, Excel o un cuaderno: comenta FUNDADOR y te escribo hoy.",
        tone: "Cierre directo y cálido.",
        energy: "65%, cálido y resolutivo.",
        gesture: "Índice señala abajo EXACTO en “comenta”. Sonrisa franca final.",
        gaze: "Al lente hasta el último frame; graba 2 s extra de aire.",
        edit: "Texto: comenta FUNDADOR 👇 (verde, rebote). Cortinilla.",
      },
    ],
    editSteps: [
      "Limpieza un pelín MENOS agresiva que en #1-#2: este video puede respirar (calma = seguridad).",
      "Seg ~8: 2 s de pantalla #9 a pantalla completa y de vuelta a ti.",
      "Chips: “✓ Pro gratis 6 meses” / “✓ Precio de fundador PARA SIEMPRE” / “✓ Mi WhatsApp directo” / “✓ Tu voz define el producto”.",
      "Zoom SOLO en “TÚ me pidas”. Sin transiciones de sonido: todo corte seco.",
      "Música “inspiring minimal” o piano suave al 12-15 (más baja que en los otros: tu voz ES el video).",
      "Cortinilla al final.",
    ],
    screenTexts: [
      { layer: "titulo", text: "busco 15 negocios (y no les voy a cobrar)", from: 0, to: 3, place: "Tercio superior", style: "“15” en verde, entrada Emerger" },
      { layer: "chip", text: "✓ Pro gratis 6 meses / ✓ Precio para siempre / ✓ Mi WhatsApp / ✓ Tu voz define", from: 12, to: 24, place: "Columna izquierda", style: "✓ verde, texto blanco" },
      { layer: "titulo", text: "solo 15 · onboarding personal", from: 24, to: 30, place: "Tercio superior", style: "“15” verde" },
      { layer: "titulo", text: "comenta FUNDADOR 👇", from: 31, to: 35, place: "Centro", style: "“FUNDADOR” verde, entrada Rebote" },
      { layer: "subtitulos", text: "Lo que dices", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: 15, gratis, para siempre, TÚ, FUNDADOR" },
    ],
    rhythm: [
      "Tu video más CALMADO: seguridad > velocidad. Sin gritos, sin hype. Arco 60→60→70→50→65.",
      "Micro-silencios (0.5 s): tras “es al revés” y tras “¿Por qué solo 15?”.",
      "Sonríe en “es al revés”, en “las mismas horas que el tuyo” y al final. El resto: gesto neutro-seguro.",
    ],
    mistakes: [
      "Sonar a vendedor de TV (“¡¡aprovecha YA!!”): la oferta es fuerte por sí sola; dila como un hecho.",
      "Listar los beneficios de corrido sin pausas: son 4 frases separadas, con su chip cada una.",
      "No fijarlo en los perfiles tras publicarlo: fijarlo es la mitad del valor de este video.",
      "Regrabarlo 20 veces buscando perfección: “seguro y natural” le gana a “perfecto y tieso”.",
    ],
  },

  // ============================================================ #5
  {
    videoId: 5,
    badge: "El primero que debes GRABAR",
    general: {
      problem: "El espectador no imagina cómo se ve “tener el negocio bajo control”; este video se lo hace SENTIR.",
      audience: "Cualquier emprendedor; en especial quien ya vio un video de dolor tuyo.",
      note: "Por qué grabarlo primero: 90% es grabación de pantalla + tu voz leyendo tranquilo. Solo 1.5 s de tu cara al final. Cero presión.",
    },
    prep: {
      ropa: "La que sea (solo sales 1.5 s; para ese clip, camiseta lisa).",
      fondo: "Para el clip final: tu escritorio de siempre.",
      camara: "La protagonista es la grabadora de pantalla del teléfono (menú rápido → Grabar pantalla).",
      plano: "Clip final: primer plano (60 cm), sonrisa tranquila, UNA frase.",
      recursos: [
        "Grabación de pantalla #1 (dashboard + prioridades) hecha LENTO y con el dedo firme",
        "Grabación de pantalla #6 (quién te debe)",
        "Voz en off grabada con audífonos-micrófono (aquí SÍ puedes leer el guion: no se te ve)",
        "Clip de tu cara 1.5 s + cortinilla",
      ],
    },
    segments: [
      {
        from: 0, to: 3, visual: "Dedo abriendo Zentro → dashboard",
        say: "Son las 7 de la mañana. Abro la app de mi negocio...",
        tone: "Voz en off tranquila, como pensando en voz alta.",
        energy: "30%: serenidad absoluta. Este video vende CALMA.",
        camera: "Grabación de pantalla: dedo LENTO, deliberado; una acción por vez.",
        edit: "Texto: POV: tu negocio te dice qué hacer HOY. SFX notificación suave. Música lo-fi al 18 desde seg 0.",
      },
      {
        from: 3, to: 10, visual: "Centro de Prioridades",
        say: "...y ya sé exactamente qué hacer hoy: cobrarle a Marta la factura vencida, confirmar el pedido de Luis... y esta semana entran 340 dólares.",
        tone: "Serena, sin prisa; sonríe levemente al decir la cifra (se oye).",
        energy: "35%, constante.",
        camera: "La pantalla se queda quieta; los 3 zooms los pone la edición, no tu dedo.",
        edit: "3 zooms suaves (105-110%), uno por ítem al nombrarlo. Cifra en verde en el subtítulo. SFX pop ×3.",
      },
      {
        from: 10, to: 17, visual: "2 s por “quién te debe” y vuelve",
        say: "No lo pensé yo. No revisé seis aplicaciones. La app lo calculó sola, con mis ventas y mis facturas.",
        tone: "Igual de serena; “sola” con una pizca de orgullo.",
        energy: "35%.",
        camera: "Corte seco entre pantallas; nada de zooms aquí (deja respirar).",
        edit: "“sola” en verde. Sin efectos: el descanso visual prepara el final.",
      },
      {
        from: 17, to: 22, visual: "TU CARA por primera vez (1.5 s) + cortinilla",
        say: "Así se siente tener el control. Es gratis: link en bio.",
        tone: "Sonrisa tranquila, no eufórica. Una sola frase, limpia.",
        energy: "50%: el único “despertar” del video.",
        body: "Primer plano, quieto, hombros relajados.",
        camera: "Fija, 60 cm, altura de ojos.",
        gaze: "Al lente.",
        edit: "La aparición de tu cara ES la sorpresa. Texto: gratis · link en bio (“gratis” en verde). Cortinilla.",
      },
    ],
    editSteps: [
      "Línea de tiempo: pantalla #1 → #6 → tu clip de cara → cortinilla. Voz en off debajo de todo.",
      "Recorta la pantalla para que cada cosa nombrada aparezca JUSTO cuando la nombras (prueba y error, 10 min).",
      "3 zooms suaves con keyframes en seg 3-10, uno por ítem.",
      "Música lo-fi al 18; bájala a 12 si compite con tu voz.",
      "Subtítulos automáticos sobre la voz en off, como siempre.",
    ],
    screenTexts: [
      { layer: "titulo", text: "POV: tu negocio te dice qué hacer HOY", from: 0, to: 5, place: "Tercio superior", style: "“HOY” en verde, entrada Emerger" },
      { layer: "titulo", text: "gratis · link en bio", from: 18, to: 22, place: "Centro", style: "“gratis” en verde" },
      { layer: "subtitulos", text: "La voz en off completa", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: qué hacer hoy, 340, sola, gratis" },
    ],
    rhythm: [
      "TODO el video es lento y sereno — el único así del lote, a propósito: vende CALMA.",
      "La única “subida” es tu cara al final: sonrisa tranquila, energía 50%, no euforia.",
    ],
    mistakes: [
      "Mover el dedo rápido en la grabación de pantalla: el espectador se pierde. Lento y deliberado.",
      "Poner música movida: mata la sensación de control. Lo-fi suave o piano.",
      "Saltarte el clip de tu cara “porque da pena”: esos 1.5 s convierten un screencast en un video de fundador.",
      "Inventar datos exagerados: usa los del usuario de prueba, creíbles ($340, no $50.000).",
    ],
  },

  // ============================================================ #6
  {
    videoId: 6,
    general: {
      problem: "El espectador confunde “lo vendido” con “lo ganado” — igual que tú antes. Verte fallar le da permiso de aprender.",
      audience: "Emprendedores activos que nunca calcularon su ganancia real.",
      note: "CTA de guardar (save): el algoritmo lo premia más que el like. Pide guardar, no seguir.",
    },
    prep: {
      ropa: "Camiseta lisa (distinta a la del resto del batch).",
      fondo: "Escritorio habitual.",
      camara: "Fija, vertical, altura de ojos, a ~70 cm.",
      plano: "Primer plano amplio: confesión con espacio para una mano.",
      recursos: [
        "Grabación de pantalla #5: ganancia real del mes (número verde)",
        "Opcional: papel con un cálculo tachado (utilería del “antes”)",
        "Cortinilla",
      ],
    },
    segments: [
      {
        from: 0, to: 3, visual: "Tú",
        say: "Perdí plata seis meses seguidos... y yo creía que estaba ganando.",
        tone: "Confesión directa, sin drama actuado.",
        energy: "50%: dolor real se cuenta sereno.",
        body: "Sentado, ligeramente encorvado (derrota física sutil), manos fuera de cuadro.",
        camera: "Fija, primer plano.",
        gesture: "Una mueca breve de dolor en “perdí plata” (labios apretados, no teatro).",
        gaze: "Al lente; baja la mirada medio segundo tras “ganando” (vergüenza) y súbela.",
        edit: "Texto: perdí plata 6 MESES sin darme cuenta (6 MESES en verde). Música tensa suave al 12.",
      },
      {
        from: 3, to: 12, visual: "Tú",
        say: "Mi error: creía que lo que vendía era lo que ganaba. Nunca resté las compras. Ni los gastos hormiga: el domicilio, la bolsa, el datáfono, el “ahorita lo anoto”.",
        tone: "Enumerando con ritmo; cada gasto hormiga es un golpecito.",
        energy: "60%, subiendo con la lista.",
        body: "Endereza la espalda al empezar (“ya lo superé, ahora te cuento”).",
        camera: "Fija; cortes entre cada gasto hormiga.",
        gesture: "Cuenta los gastos con los dedos; comillas en “ahorita lo anoto”.",
        gaze: "Al lente.",
        edit: "Corte por cada gasto. Chips pequeños acumulándose: compras / domicilio / bolsas / datáfono. SFX pop ×4.",
      },
      {
        from: 12, to: 20, visual: "Tú, frenazo",
        say: "El mes que por fin lo calculé bien... mi “ganancia” era la MITAD de lo que yo creía.",
        tone: "Lento, grave. “la MITAD” se dice separando las sílabas.",
        energy: "Frenazo a 35%. Es EL dato del video.",
        body: "Quieto total.",
        camera: "Fija; zoom de edición 112% en “la MITAD”.",
        gesture: "Sin gestos. La quietud vende el golpe.",
        gaze: "Clavada al lente + 0.5 s de silencio después.",
        edit: "MÚSICA A CERO en este bloque. Zoom en “la MITAD”. Texto: era la MITAD (verde).",
      },
      {
        from: 20, to: 30, visual: "Pantalla #5",
        say: "Hoy lo veo así: ingresos, menos gastos, menos compras. Un solo número, verde si gano, rojo si no. Sin fórmulas, sin cuaderno, sin mentirme.",
        tone: "Voz en off de alivio ordenado.",
        energy: "55%.",
        camera: "Pantalla #5 lenta; el número final se muestra 2 s quieto.",
        edit: "Whoosh (solo sonido) al entrar. Zoom suave al número verde. Vuelve música al 15.",
      },
      {
        from: 30, to: 35, visual: "Tú + cortinilla",
        say: "El número que importa no es cuánto vendes. Es cuánto te QUEDA. Guárdate este video para el cierre del mes.",
        tone: "Sentencia + recomendación de amigo.",
        energy: "65%, cierre firme.",
        gesture: "Índice toca la sien en “el número que importa”; señala abajo en “guárdate”.",
        gaze: "Al lente.",
        edit: "Texto: guárdalo para fin de mes 🔖. Cortinilla.",
      },
    ],
    editSteps: [
      "Estructura de sonido: música tensa 12 → chips con pops → SILENCIO en el dato (seg 12-20) → whoosh a pantalla → música 15.",
      "Chips de gastos hormiga acumulándose (pop ×4), fuera de golpe en el frenazo.",
      "Zoom 112% en “la MITAD” — el único zoom fuerte del video.",
      "Pantalla #5: número final quieto 2 s (que se lea).",
      "Subtítulos: verde en 6 MESES, la MITAD, te QUEDA.",
    ],
    screenTexts: [
      { layer: "titulo", text: "perdí plata 6 MESES sin darme cuenta", from: 0, to: 3, place: "Tercio superior", style: "“6 MESES” en verde, entrada Emerger" },
      { layer: "chip", text: "compras / domicilio / bolsas / datáfono", from: 5, to: 12, place: "Columna izquierda", style: "Blanco, pop al aparecer" },
      { layer: "titulo", text: "era la MITAD", from: 15, to: 20, place: "Centro", style: "“MITAD” en verde, entrada Emerger" },
      { layer: "titulo", text: "guárdalo para fin de mes 🔖", from: 31, to: 35, place: "Centro", style: "Blanco, entrada Rebote" },
      { layer: "subtitulos", text: "Todo lo que dices", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: 6 meses, la mitad, te queda" },
    ],
    rhythm: [
      "Arco: confesión (50%) → lista rítmica (60%) → FRENAZO con el dato (35%) → alivio (55%) → sentencia (65%).",
      "El silencio musical del seg 12-20 es obligatorio: sin él, el dato no pega.",
      "No sonrías hasta el bloque de la solución.",
    ],
    mistakes: [
      "Dramatizar de más la pérdida: cuenta el error como quien ya lo superó, no como tragedia.",
      "Decir cifras exactas de TU negocio si no quieres: “la mitad” funciona mejor que un número real aquí.",
      "Saltarte el silencio del bloque 3.",
      "CTA de “sígueme” en vez de “guárdalo”: este video es de utilidad, pide save.",
    ],
  },

  // ============================================================ #7
  {
    videoId: 7,
    general: {
      problem: "Ver el proceso crea pertenencia: el espectador pasa de curioso a seguidor de la historia.",
      audience: "Early adopters, otros makers y emprendedores que quieren ver “cómo se hace”.",
      note: "FORMATO REPETIBLE: cada semana cambias el contenido de los 3 bloques centrales y el número de semana. Graba el episodio SIEMPRE el mismo día (domingo, al final del batch).",
    },
    prep: {
      ropa: "Camiseta lisa; puedes verte más casual (es detrás de cámaras).",
      fondo: "Monitor con el CÓDIGO del proyecto bien visible (aquí es protagonista).",
      camara: "Fija, vertical, altura de ojos, a ~80 cm. Para el b-roll: cámara en mano apuntando al monitor 10 s.",
      plano: "Plano medio. El b-roll de código puede ser cámara en mano (lo “sucio” suma).",
      recursos: [
        "Grabación de pantalla #10: editor de código con el proyecto (20-30 s)",
        "Pantalla de la feature nueva de la semana",
        "Plantilla de texto “SEMANA N” (misma posición siempre: branding de serie)",
        "Cortinilla",
      ],
    },
    segments: [
      {
        from: 0, to: 4, visual: "Tú, enérgico + flash de código 1 s",
        say: "Estoy construyendo una app en público. Semana uno: pasaron tres cosas.",
        tone: "Enérgico, de reporte rápido.",
        energy: "80% desde el frame 1: los episodios de serie abren arriba.",
        body: "Sentado al borde de la silla, torso hacia la cámara.",
        camera: "Fija; flash de 1 s del código (pantalla #10) insertado en “construyendo”.",
        gesture: "Tres dedos arriba en “tres cosas”.",
        gaze: "Al lente.",
        edit: "Texto GRANDE: SEMANA 1 (posición fija para toda la serie). Música rítmica al 18.",
      },
      {
        from: 4, to: 14, visual: "Pantalla de la feature nueva",
        say: "Uno: construí [la feature de la semana — descríbela en una frase y muestra cómo se usa].",
        tone: "Voz en off ágil, concreta.",
        energy: "75%.",
        camera: "Grabación de pantalla de la feature, lenta, 8-10 s.",
        edit: "Chip “1” en esquina. Zoom a lo importante de la pantalla. SFX pop.",
      },
      {
        from: 14, to: 26, visual: "Tú (el mejor momento del video)",
        say: "Dos: se me rompió [lo que se rompió]. Y aprendí [la lección en una frase honesta].",
        tone: "Honesto, con media sonrisa de “así es esto”.",
        energy: "60%: bajar aquí hace creíble todo lo demás.",
        body: "Reclínate 5 cm (relajación = confianza al confesar).",
        camera: "Fija, de vuelta a ti.",
        gesture: "Manos abiertas en “se me rompió” (gesto de “se me cayó”).",
        gaze: "Al lente; puedes mirar 1 s al monitor de atrás señalándolo con el pulgar.",
        edit: "Chip “2”. Sin música 2 s en la confesión (mini-frenazo) y vuelve.",
      },
      {
        from: 26, to: 34, visual: "Tú + teaser",
        say: "Y tres: la próxima semana viene [teaser en 5 palabras]. No te lo pierdas.",
        tone: "Teaser de serie, con intriga ligera.",
        energy: "75%, subiendo al cierre.",
        gesture: "Ceja arriba en el teaser.",
        gaze: "Al lente.",
        edit: "Chip “3” + texto del teaser en el tercio superior.",
      },
      {
        from: 34, to: 40, visual: "Tú + cortinilla",
        say: "¿Qué le agregarías tú? Los mejores comentarios entran directo al roadmap. En serio.",
        tone: "Invitación genuina; “en serio” con mirada sostenida.",
        energy: "70%.",
        gesture: "Índice señala abajo en “comentarios”.",
        gaze: "Al lente hasta el final.",
        edit: "Texto: tu comentario → mi roadmap. Cortinilla.",
      },
    ],
    editSteps: [
      "Plantilla de serie: “SEMANA N” siempre igual y en el mismo lugar — guarda el proyecto de CapCut como plantilla y duplica cada semana.",
      "Estructura fija 1-2-3 con chips numerados (pop en cada uno).",
      "Mini-frenazo musical en la confesión del bloque 2 (2 s sin música).",
      "Ritmo: corte cada 2-3 s en tus bloques; la pantalla de la feature puede respirar 8-10 s.",
      "Guarda cada episodio en una playlist/carpeta “Construyendo Zentro” en cada red.",
    ],
    screenTexts: [
      { layer: "titulo", text: "SEMANA 1", from: 0, to: 4, place: "Tercio superior, posición FIJA de la serie", style: "Blanco gigante, entrada Emerger" },
      { layer: "chip", text: "1 / 2 / 3 (numeración de bloques)", from: 4, to: 34, place: "Esquina superior izquierda", style: "Verde, pop al cambiar" },
      { layer: "titulo", text: "tu comentario → mi roadmap", from: 35, to: 40, place: "Centro", style: "“roadmap” en verde" },
      { layer: "subtitulos", text: "Todo", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: semana 1, roadmap" },
    ],
    rhythm: [
      "Abre a 80% (serie), baja a 60% en la confesión (bloque más importante), cierra a 70-75%.",
      "La confesión honesta del bloque “dos” es lo que diferencia esta serie de un changelog aburrido.",
      "Máximo 40 s por episodio: si una semana pasó mucho, guarda material para el siguiente.",
    ],
    mistakes: [
      "Convertirlo en changelog técnico (“refactoricé el módulo X”): traduce TODO a beneficio de negocio.",
      "Saltarte la parte de “se me rompió”: sin vulnerabilidad no hay serie, hay publicidad.",
      "Cambiar el diseño del “SEMANA N” cada episodio: la repetición ES el branding.",
      "Prometer en el teaser algo que no sabes si estará: teaser vago > promesa rota.",
    ],
  },

  // ============================================================ #8
  {
    videoId: 8,
    general: {
      problem: "Tu palabra sola vale menos que la de un tercero: aquí el dolor lo valida una emprendedora real.",
      audience: "Revendedoras y quien fía — se verán en ella.",
      note: "NECESITA una persona real con permiso (conocida tuya con negocio). NO se actúa: si la reacción es fingida, se nota y destruye la confianza. Plan B sin persona: recrear la conversación con capturas de chat reales (con permiso).",
    },
    prep: {
      ropa: "La tuya: casual. Ella: como esté (autenticidad).",
      fondo: "SU espacio de trabajo (tienda, mesa con productos): contexto real.",
      camara: "Cámara en mano (único video así del lote): sujeta el celular vertical con las dos manos, codos pegados al cuerpo para estabilizar.",
      plano: "Plano medio de ella; tú puedes no salir (tu voz pregunta).",
      recursos: [
        "Permiso explícito de ella (y confirmar si quiere salir con nombre o anónima)",
        "Calculadora o Zentro a mano para sumar en vivo",
        "Cortinilla",
      ],
    },
    segments: [
      {
        from: 0, to: 3, visual: "Ella, reaccionando (el clip más fuerte VA PRIMERO)",
        say: "(su reacción real: “¿¡TANTO!?” o la que salga) — tú en texto: Le deben $X y no lo sabía.",
        tone: "El clip de la reacción se pone de gancho aunque cronológicamente ocurra después.",
        energy: "La de ella, real.",
        camera: "En mano, estable, a 1 m de ella.",
        edit: "Texto: le deben $X y no lo sabía (cifra en verde). SIN música: el audio real es el gancho.",
      },
      {
        from: 3, to: 10, visual: "Tú preguntas, ella piensa",
        say: "Tú (voz): “¿Cuánto te deben tus clientes ahorita? Número exacto.” — Ella: duda, cuenta en voz alta, se ríe nerviosa.",
        tone: "Tu pregunta: casual, curiosa, sin tono de examen.",
        energy: "Conversación normal (50%).",
        camera: "Quieta sobre ella; deja que el silencio de ella respire (NO lo cortes todo).",
        gaze: "Ella puede mirar al aire mientras calcula: eso es oro, no lo edites fuera.",
        edit: "Subtítulos de TODO (su audio puede no ser nítido). Timer sutil en pantalla mientras piensa.",
      },
      {
        from: 10, to: 20, visual: "La suma en vivo",
        say: "Ella suma con tu ayuda: “...la señora del kilo y medio... lo de mi cuñada... lo del catálogo...”. Aparece el número real.",
        tone: "Natural; tú solo asientes y ayudas a sumar.",
        energy: "Sube sola con el número.",
        camera: "Baja el celular a las manos/calculadora 3-4 s y vuelve a su cara para la reacción REAL (la del gancho).",
        edit: "El número final GIGANTE en verde con SFX cha-ching invertido (grave). Zoom a su cara en la reacción.",
      },
      {
        from: 20, to: 27, visual: "Tú a cámara (o voz en off sobre su reacción congelada)",
        say: "No es un caso raro. Es el estándar: nadie que lleve el negocio en la cabeza sabe el número exacto. Por eso construí una app que te lo dice al abrirla.",
        tone: "Conclusión serena, sin burlarte de ella jamás.",
        energy: "55%.",
        camera: "Si sales tú: primer plano rápido donde estés (la luz que haya).",
        edit: "Flash de 2 s de pantalla #6 (quién te debe) en “te lo dice al abrirla”.",
      },
      {
        from: 27, to: 30, visual: "Cierre",
        say: "¿Tú sí sabes cuánto te deben? Número exacto. Te leo abajo.",
        tone: "Reto amistoso.",
        energy: "65%.",
        edit: "Texto: ¿cuánto te deben A TI? 👇. Cortinilla.",
      },
    ],
    editSteps: [
      "REGLA DE ORO: la reacción real de ella va de gancho (seg 0) aunque ocurra a mitad de la conversación.",
      "No cortes todos los silencios de ella al calcular: 1-2 s de duda son la prueba de autenticidad.",
      "Número final gigante en verde + zoom a su cara.",
      "Sin música hasta el seg ~20; entra suave con tu conclusión.",
      "Pídele aprobación del corte final ANTES de publicar (y respétala si pide cambios).",
    ],
    screenTexts: [
      { layer: "titulo", text: "le deben $X y no lo sabía", from: 0, to: 3, place: "Tercio superior", style: "Cifra en verde, entrada Emerger" },
      { layer: "titulo", text: "¿cuánto te deben A TI? 👇", from: 27, to: 30, place: "Centro", style: "“A TI” en verde, Rebote" },
      { layer: "subtitulos", text: "TODA la conversación (el audio en exteriores es irregular)", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en las cifras" },
    ],
    rhythm: [
      "Este video lo edita la realidad: tu único trabajo es no matar los momentos genuinos.",
      "El silencio de ella calculando ES el contenido. Déjalo respirar.",
    ],
    mistakes: [
      "Actuarlo con alguien fingiendo sorpresa: se nota SIEMPRE y destruye todo. Si no hay persona real, usa el plan B de capturas.",
      "Burlarte o dejar que el video la haga ver mal: el tono es “nos pasa a todos”, no “mira qué desordenada”.",
      "Publicar sin su aprobación del corte final.",
      "Sobre-editar: aquí menos cortes = más verdad.",
    ],
  },

  // ============================================================ #9
  {
    videoId: 9,
    general: {
      problem: "Los SaaS se sienten fríos; este video muestra que Zentro celebra CONTIGO — producto con alma.",
      audience: "Quien ya vio algún video tuyo y está decidiendo si Zentro es distinto.",
      note: "El CTA pide ideas en comentarios: es investigación de producto disfrazada de video.",
    },
    prep: {
      ropa: "Camiseta lisa.",
      fondo: "Escritorio con código visible.",
      camara: "Fija, vertical, altura de ojos, a ~70 cm.",
      plano: "Primer plano amplio.",
      recursos: [
        "Grabación de pantalla #4: “Cobraste $X de <cliente>” + ¡Factura saldada!",
        "Cortinilla",
      ],
    },
    segments: [
      {
        from: 0, to: 3, visual: "Tú",
        say: "Programé un botón que solo existe para hacerte sentir bien.",
        tone: "Orgullo travieso, como quien confiesa una travesura buena.",
        energy: "60%.",
        body: "Inclinado levemente adelante, como compartiendo un secreto.",
        camera: "Fija.",
        gesture: "Media sonrisa desde el frame 1 (este video ES cálido).",
        gaze: "Al lente.",
        edit: "Texto: un botón solo para sentirte BIEN (“BIEN” en verde). Música cálida al 15.",
      },
      {
        from: 3, to: 10, visual: "Tú",
        say: "Piénsalo: cobrar una deuda vieja se siente INCREÍBLE. Y ninguna app lo celebra. Registras el pago y... nada. Silencio. Como si no importara.",
        tone: "Construye la injusticia con humor suave.",
        energy: "65%; “nada. Silencio.” se dice lento y plano (imitando la frialdad).",
        gesture: "Brazos caen flojos en “nada” (gesto de decepción cómica).",
        gaze: "Al lente; mirada al vacío 1 s en “silencio” y regresa.",
        edit: "Corte seco tras “INCREÍBLE”. En “nada. Silencio.” la música SE CORTA 1.5 s (chiste sonoro) y vuelve.",
      },
      {
        from: 10, to: 20, visual: "Pantalla #4",
        say: "Por eso en Zentro, cuando cobras, la app te lo dice con todas las letras: “Cobraste 80 dólares de Marta. ¡Factura saldada!”. Porque los números también son emociones.",
        tone: "Voz en off disfrutándolo; la frase final es LA frase del video.",
        energy: "70%.",
        camera: "Pantalla #4: el momento del pago registrado → aparece la celebración. Déjala 2 s quieta.",
        edit: "SFX cha-ching EXACTO cuando aparece “Cobraste $X”. Zoom suave 108% al mensaje. “emociones” en verde.",
      },
      {
        from: 20, to: 25, visual: "Tú + cortinilla",
        say: "Dime: ¿qué momento de tu negocio merece celebrarse? Lo leo... y lo programo.",
        tone: "Invitación juguetona pero literal.",
        energy: "65%.",
        gesture: "Índice a la sien en “lo programo” (gesto de “lo apunto”).",
        gaze: "Al lente.",
        edit: "Texto: ¿qué celebro? tú pides, yo programo 👇. Cortinilla.",
      },
    ],
    editSteps: [
      "El chiste sonoro del seg ~8 (música cortada 1.5 s en “nada. Silencio.”) es el corazón de la edición: pruébalo hasta que dé risa.",
      "Cha-ching sincronizado AL FRAME con la aparición del mensaje de cobro.",
      "Pantalla #4 quieta 2 s para que se LEA la celebración.",
      "Música cálida (buscar “feel good acoustic”) al 15.",
    ],
    screenTexts: [
      { layer: "titulo", text: "un botón solo para sentirte BIEN", from: 0, to: 3, place: "Tercio superior", style: "“BIEN” en verde, Emerger" },
      { layer: "titulo", text: "los números también son EMOCIONES", from: 16, to: 20, place: "Tercio superior", style: "“EMOCIONES” en verde" },
      { layer: "titulo", text: "tú pides, yo programo 👇", from: 21, to: 25, place: "Centro", style: "Blanco, Rebote" },
      { layer: "subtitulos", text: "Todo", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: increíble, cobraste, emociones" },
    ],
    rhythm: [
      "Cálido de inicio a fin (60-70%): es el video más “sonriente” del lote.",
      "El único bajón es actuado: “nada. Silencio.” — frialdad cómica de 1.5 s.",
    ],
    mistakes: [
      "Contarlo como feature técnica (“implementé un banner de confirmación”): es una decisión EMOCIONAL.",
      "No sincronizar el cha-ching con el mensaje: sin eso el momento no existe.",
      "Ignorar los comentarios que respondan al CTA: cada uno es investigación de producto gratis — responde TODOS.",
    ],
  },

  // ============================================================ #10
  {
    videoId: 10,
    general: {
      problem: "El rival de Zentro no es otra app: es el Excel y la costumbre. Este video hace VISIBLE la fricción.",
      audience: "El emprendedor de Excel que “ya tiene su sistema”.",
      note: "Necesita 2 escenarios (laptop y teléfono). Es el más laborioso del lote — grábalo cuando ya tengas ritmo.",
    },
    prep: {
      ropa: "La misma en ambos lados (eres tú vs tú).",
      fondo: "Lado A: laptop en el escritorio. Lado B: tú de pie con el teléfono.",
      camara: "Dos tomas fijas: A) plano medio frente a la laptop; B) primer plano amplio con el teléfono en mano visible.",
      plano: "A: plano medio con laptop. B: primer plano amplio.",
      recursos: [
        "Grabación de pantalla #2: venta rápida en 3 taps",
        "Excel real (o recreado) con muchas filas para el lado A",
        "Cortinilla",
      ],
    },
    segments: [
      {
        from: 0, to: 3, visual: "Pantalla dividida (A y B congelados)",
        say: "Registrar UNA venta. Mi yo del pasado... contra mi yo de hoy.",
        tone: "De presentador de duelo, con humor.",
        energy: "70%.",
        camera: "Pantalla dividida vertical (máscara en CapCut, gratis): A arriba, B abajo.",
        edit: "Texto: ANTES vs AHORA. Timer “00:00” aparece en ambos lados. Música rítmica 18.",
      },
      {
        from: 3, to: 15, visual: "Lado A (tú con laptop, hastío actuado)",
        say: "(sin hablar; suspiras) — voz en off: Abrir la laptop. Buscar el archivo. ¿Ventas-2026-FINAL o FINAL-FINAL? Fila 847. Y la fórmula... rota.",
        tone: "Voz en off de documentalista aguantando la risa.",
        energy: "El personaje A: 20% (drenado). Tu voz en off: 60%.",
        body: "Actúa el hastío: hombros caídos, mentón en la mano, scroll infinito con un dedo.",
        camera: "Fija sobre ti y la laptop; que se vea el scroll.",
        gesture: "Mirada de súplica al techo cuando aparece la fórmula rota.",
        gaze: "A la laptop (aquí NO miras al lente: estás sufriendo).",
        edit: "Timer del lado A corriendo con SFX tick-tock. Zoom al Excel caótico. El timer llega a 1:47 y sigue...",
      },
      {
        from: 15, to: 22, visual: "Lado B (tú con el teléfono)",
        say: "Mi yo de hoy: botón más... ochenta... listo. Tres segundos. Desde la fila del banco.",
        tone: "Ligero, casi aburrido de lo fácil.",
        energy: "75%: la agilidad se siente en la voz.",
        body: "De pie, relajado, teléfono en una mano.",
        camera: "Fija; inserta la pantalla #2 (3 taps) a pantalla completa 3 s.",
        gesture: "Enseña el teléfono a cámara al decir “listo”.",
        gaze: "Al lente (aquí SÍ, todo el tiempo).",
        edit: "Timer del lado B: 0:03 congelado en verde + SFX pop-pop-pop (uno por tap). El timer de A sigue corriendo de fondo (chiste visual).",
      },
      {
        from: 22, to: 30, visual: "Tú a cámara + cortinilla",
        say: "No odias los números. Odias la FRICCIÓN. Quítala, y tu negocio se registra solo. Link en bio, gratis.",
        tone: "Sentencia + cierre directo.",
        energy: "70%.",
        gesture: "Chasquido de dedos en “quítala”.",
        gaze: "Al lente.",
        edit: "Texto: no odias los números, odias la FRICCIÓN (verde). Cortinilla.",
      },
    ],
    editSteps: [
      "Pantalla dividida con máscara (gratis): mitades superior/inferior; congela el lado inactivo.",
      "Los DOS timers son el chiste: A (tick-tock, no para) vs B (0:03 verde congelado).",
      "SFX: tick-tock en A, pop ×3 en B (uno por tap), chasquido en “quítala”.",
      "El lado A se graba UNA vez con actuación exagerada-contenida: hastío, no payasada.",
      "Zoom al Excel caótico y a la fórmula #¡REF! si la recreas.",
    ],
    screenTexts: [
      { layer: "titulo", text: "ANTES vs AHORA", from: 0, to: 3, place: "Centro", style: "Blanco gigante, Emerger" },
      { layer: "chip", text: "Timer A (corre) / Timer B (0:03 verde)", from: 3, to: 22, place: "Esquina de cada mitad", style: "Monoespaciado, B en verde" },
      { layer: "titulo", text: "odias la FRICCIÓN", from: 23, to: 30, place: "Tercio superior", style: "“FRICCIÓN” en verde" },
      { layer: "subtitulos", text: "Voz en off + tus frases", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: 3 segundos, fricción, gratis" },
    ],
    rhythm: [
      "El contraste ES el ritmo: lado A lento y agónico (12 s), lado B veloz (7 s).",
      "No cortes demasiado el lado A: la agonía necesita durar para que el B libere.",
    ],
    mistakes: [
      "Actuar el hastío como payaso: es humor contenido (suspiros, mirada al techo), no gritos.",
      "Nombrar a Excel con desprecio: el público AMA su Excel; el enemigo es la fricción, no la herramienta.",
      "Hacer el lado B rápido pero confuso: los 3 taps deben VERSE claros en la pantalla insertada.",
    ],
  },

  // ============================================================ #11
  {
    videoId: 11,
    general: {
      problem: "“Tu voz define el producto” es una promesa; este video es la PRUEBA.",
      audience: "Indecisos que vieron el #4 y dudan si el “te escucho” es real.",
      note: "NECESITA un caso real: alguien pidió algo y tú lo construiste. Con permiso del autor del mensaje (o nombre tapado). NO SE INVENTA JAMÁS: si aún no pasó, este video espera.",
    },
    prep: {
      ropa: "Camiseta lisa.",
      fondo: "Escritorio con código.",
      camara: "Fija, vertical, altura de ojos, ~70 cm.",
      plano: "Primer plano amplio.",
      recursos: [
        "Screenshot REAL del mensaje/pedido (nombre tapado si no hay permiso)",
        "Grabación de pantalla de la feature nueva funcionando",
        "Cortinilla",
      ],
    },
    segments: [
      {
        from: 0, to: 4, visual: "Screenshot del pedido a pantalla completa",
        say: "(voz en off) Un usuario me mandó esto el lunes.",
        tone: "Intriga contenida.",
        energy: "55%.",
        camera: "El screenshot ocupa todo; zoom lento hacia la frase clave del pedido.",
        edit: "Texto: me pidió esto el LUNES (“LUNES” en verde). SFX de notificación al aparecer.",
      },
      {
        from: 4, to: 12, visual: "Tú",
        say: "Pude decirle “está en el roadmap” — la frase con la que todas las empresas te dicen que no. Pero es usuario fundador. Y su voz ES el roadmap.",
        tone: "Complicidad; comillas irónicas en “está en el roadmap”.",
        energy: "65%.",
        body: "Sentado, firme.",
        camera: "Fija.",
        gesture: "Comillas con los dedos en “está en el roadmap”; palma al pecho en “su voz ES el roadmap”.",
        gaze: "Al lente.",
        edit: "Corte seco tras “que no”. “ES el roadmap” en verde.",
      },
      {
        from: 12, to: 22, visual: "Pantalla: la feature funcionando",
        say: "Martes: lo programé. Miércoles: él lo probó. Hoy: lo tienes tú también. Así se ve.",
        tone: "Voz en off ágil, factual; los días se dicen como tambores.",
        energy: "70%.",
        camera: "Grabación de pantalla de la feature, lenta y clara.",
        edit: "Línea de tiempo animada LUN → MAR → MIÉ → HOY (chips que aparecen con pop). Zoom a lo importante.",
      },
      {
        from: 22, to: 28, visual: "Tú + cortinilla",
        say: "¿Qué le falta a Zentro para servirte a TI? Pídemelo abajo. Ya viste que va en serio.",
        tone: "Reto amable con la prueba encima de la mesa.",
        energy: "70%.",
        gesture: "Índice señala abajo en “pídemelo”.",
        gaze: "Al lente.",
        edit: "Texto: pídemelo · va EN SERIO 👇 (“EN SERIO” en verde). Cortinilla.",
      },
    ],
    editSteps: [
      "La línea de tiempo LUN→MAR→MIÉ→HOY con chips animados es la firma visual del video.",
      "El screenshot abre el video A PANTALLA COMPLETA con zoom lento (3-4 s máximo).",
      "Música rítmica constante al 15; sin frenazos (este video es momentum puro).",
      "Guarda este formato: cada vez que construyas algo pedido, repites la estructura (serie “pediste/programé”).",
    ],
    screenTexts: [
      { layer: "titulo", text: "me pidió esto el LUNES", from: 0, to: 4, place: "Tercio superior", style: "“LUNES” en verde" },
      { layer: "chip", text: "LUN → MAR → MIÉ → HOY", from: 12, to: 22, place: "Tercio superior", style: "Chips con pop secuencial, HOY en verde" },
      { layer: "titulo", text: "pídemelo · va EN SERIO 👇", from: 23, to: 28, place: "Centro", style: "“EN SERIO” en verde, Rebote" },
      { layer: "subtitulos", text: "Todo", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: lunes, ES el roadmap, hoy" },
    ],
    rhythm: [
      "Momentum constante 55→65→70→70: este video no frena nunca (la velocidad ES el mensaje).",
      "Los días (“martes”, “miércoles”, “hoy”) se pronuncian como golpes de tambor.",
    ],
    mistakes: [
      "INVENTAR el caso: si se descubre (y se descubre), pierdes todo. Sin caso real no hay video.",
      "Publicar el screenshot sin permiso o sin tapar el nombre.",
      "Explicar la feature con tecnicismos: di qué RESUELVE, no cómo está hecha.",
    ],
  },

  // ============================================================ #12
  {
    videoId: 12,
    general: {
      problem: "El espectador está entrenado para desconfiar de todo lo que parece anuncio. Este video le da la razón — y por eso funciona.",
      audience: "Los escépticos: los que vieron 3 videos y no comentaron nada.",
      note: "Es el video más fácil de grabar del lote (plano fijo, pocos cortes) y el que más confianza genera por minuto invertido.",
    },
    prep: {
      ropa: "Camiseta lisa oscura.",
      fondo: "Escritorio, luz pareja.",
      camara: "Fija, vertical, altura de ojos, ~70 cm. UN SOLO plano, sin b-roll: la sobriedad es el formato.",
      plano: "Primer plano amplio, constante.",
      recursos: ["Solo la cortinilla. Este video no lleva pantallas: es cara y verdad."],
    },
    segments: [
      {
        from: 0, to: 4, visual: "Tú, muy serio",
        say: "No quiero que me compres nada. En serio.",
        tone: "Seco, sereno, sin sonrisa. El patrón roto es que NADIE abre así.",
        energy: "40%. SIN música: el silencio incomoda y engancha.",
        body: "Quieto absoluto, espalda recta, manos fuera de cuadro.",
        camera: "Fija. Cero movimiento en TODO el video (la calma es la firma).",
        gesture: "Nada. Rostro neutro.",
        gaze: "Clavada al lente; 0.5 s de silencio tras “en serio”.",
        edit: "SIN música los primeros 5 s. Texto: no te quiero vender nada. Sin SFX.",
      },
      {
        from: 4, to: 14, visual: "Tú",
        say: "Zentro está en fase de pruebas. Cobrarte hoy sería venderte algo a medio pulir. Y eso no.",
        tone: "Explicación franca; “y eso no” con firmeza suave.",
        energy: "45%.",
        body: "Igual de quieto.",
        gesture: "Un gesto único: negación lenta con la cabeza en “y eso no”.",
        gaze: "Al lente.",
        edit: "Entra música mínima (piano una nota, “minimal piano”) al 8. Corte seco por frase, pero POCOS: 3-4 en total.",
      },
      {
        from: 14, to: 24, visual: "Tú",
        say: "Lo que necesito son 15 negocios que lo usen gratis y me digan la verdad: qué sirve, qué estorba, qué falta. Tú ganas una app gratis con el programador en tu WhatsApp. Yo gano un producto que sirva de verdad.",
        tone: "Trato justo expuesto con las palmas abiertas.",
        energy: "55%.",
        gesture: "Palmas abiertas hacia arriba en “tú ganas... yo gano” (una mano por cada parte del trato).",
        gaze: "Al lente.",
        edit: "Chips minimalistas: TÚ: app gratis + soporte / YO: la verdad. “la verdad” en verde.",
      },
      {
        from: 24, to: 30, visual: "Tú + cortinilla",
        say: "Cuando esté listo y lo cobre, tú tendrás precio de fundador para siempre. Trato justo. Si esto te suena honesto... ya sabes dónde está el link.",
        tone: "Cierre sobrio; la última frase casi como quien se encoge de hombros.",
        energy: "50%. NO subas al final: la contención es el mensaje.",
        gesture: "Media sonrisa mínima SOLO en la última frase.",
        gaze: "Al lente hasta el final.",
        edit: "Texto: si te suena honesto → link en bio. Cortinilla SIN subir la música.",
      },
    ],
    editSteps: [
      "ANTI-EDICIÓN deliberada: 6-8 cortes en total (vs 15-20 de los otros), cero zooms, cero SFX de pop.",
      "Sin música los primeros 5 s; luego piano mínimo al 8 constante.",
      "Los subtítulos y 3 textos son la única capa visual.",
      "Exporta y compáralo con el #2: deben sentirse de mundos distintos. Ese contraste en tu feed es intencional.",
    ],
    screenTexts: [
      { layer: "titulo", text: "no te quiero vender nada", from: 0, to: 4, place: "Tercio superior", style: "Blanco, sin animación (aparece seca)" },
      { layer: "chip", text: "TÚ: app gratis + soporte / YO: la verdad", from: 14, to: 24, place: "Columna izquierda", style: "Minimal, “la verdad” en verde" },
      { layer: "titulo", text: "si te suena honesto → link en bio", from: 25, to: 30, place: "Centro", style: "“honesto” en verde, sin rebote" },
      { layer: "subtitulos", text: "Todo", from: 0, to: "fin", place: "Centro-bajo", style: "Verde en: pruebas, gratis, la verdad, fundador" },
    ],
    rhythm: [
      "Plano energético BAJO todo el video (40-55%): la contención es el diferencial.",
      "Los 0.5 s de silencio tras “en serio” son sagrados.",
      "PROHIBIDO el arco típico de cierre arriba: termina sobrio.",
    ],
    mistakes: [
      "Meterle ritmo “porque se siente lento”: lento ES el formato. Un video calmado entre mil acelerados detiene el scroll.",
      "Sonreír de más: máximo una media sonrisa al final.",
      "Añadir pantallas de la app: este video es solo tu palabra. Meterle producto lo convierte en el anuncio que dice no ser.",
    ],
  },
];

export function getScript(videoId: number): Script | undefined {
  return SCRIPTS.find((s) => s.videoId === videoId);
}
