import type { Video } from "./types";

// Fuente: Marketing-Assets-Zentro/Guiones-60-Videos-Zentro.md (versión refinada 2026-07-07).
// El documento queda como respaldo; el trabajo diario es sobre esta estructura.
// Escala de scores: 1 baja · 2 media · 3 alta · 4 muy alta.

const ALL: Video["platforms"] = ["tiktok", "reels", "facebook"];

export const VIDEOS: Video[] = [
  // ——— Guiones con producción completa (1-12) ———
  {
    id: 1,
    title: "Te deben dinero y te da pena cobrar",
    pillar: "P1",
    objective: "Primer video con tu cara: que quien fía se identifique y comente COBRA.",
    problem: "La vergüenza de cobrar — le pone nombre y le muestra una salida.",
    hook: "“A ti te deben dinero... y te da pena cobrarlo. Admítelo.” (primer plano, tono de secreto)",
    cta: "Comenta COBRA y te escribo · link en bio, gratis",
    durationSec: 30,
    effortMin: 25,
    emotions: ["identificación", "alivio con humor"],
    audience: "Emprendedores que fían: revendedoras, servicios, negocios familiares",
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 2, confianza: 2, fundadores: 3, explica: 2 },
    summary:
      "Confesión del dolor de cobrar → el 'holaa, disculpa que te moleste' → “cobrar es incómodo, para todos” → Zentro manda el recordatorio por ti → 6 meses gratis a los primeros 15.",
    detailed: true,
  },
  {
    id: 2,
    title: "Tu negocio vive en 6 lugares",
    pillar: "P1",
    objective: "El espejo del caos: que el desordenado-funcional se reconozca y comente. Siembra, no vende.",
    problem: "Le muestra POR QUÉ se siente desbordado: su negocio está regado en 6 sitios.",
    hook: "“Tu negocio vive en 6 lugares. Cuéntalos conmigo.” (cuaderno arrugado en mano)",
    cta: "¿En cuántos lugares vive el tuyo? Te leo 👇",
    durationSec: 28,
    effortMin: 25,
    emotions: ["reconocimiento", "agobio que se vuelve risa"],
    audience: "El emprendedor que vende bien pero vive apagando incendios",
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 2, fundadores: 2, explica: 2 },
    summary:
      "6 lugares contados con dedos y chips en pantalla (WhatsApp, Excel, cuaderno, memoria, carpeta, galería 🐶) → “se pierde plata por no VER todo junto” → dashboard 8 s → pregunta a comentarios.",
    detailed: true,
  },
  {
    id: 3,
    title: "Cómo nació Zentro",
    pillar: "P4",
    objective: "La historia origen: el video que ven antes de confiarte sus datos. Se fija junto al #4.",
    hook: "“Pude hacer una app de facturas más. Dije que no.” + texto: renuncié a hacerla FÁCIL",
    cta: "Sígueme para ver cómo termina esta historia",
    durationSec: 45,
    effortMin: 35,
    emotions: ["curiosidad", "inspiración tranquila"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 2, confianza: 3, fundadores: 2, explica: 3 },
    summary:
      "Storytelling (gancho→contexto→conflicto→resolución): todos tienen MIL datos y CERO respuestas → “¿y si tu negocio te dijera qué hacer hoy?” → así nació Zentro, Z de centro → serie en vivo.",
  },
  {
    id: 4,
    title: "Busco 15 negocios",
    pillar: "P5",
    objective: "El pitch honesto que convierte. FIJADO en los 3 perfiles: todo visitante lo ve primero.",
    problem: "El interesado necesita la oferta completa, clara, en 35 segundos.",
    hook: "“Busco 15 negocios. Y no, no les voy a cobrar. Es al revés.”",
    cta: "Comenta FUNDADOR y te escribo hoy · link en bio",
    durationSec: 35,
    effortMin: 30,
    emotions: ["sentirse elegido", "confianza por honestidad"],
    audience: "Quien ya te vio 1-2 veces y evalúa entrar",
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 1, facilidad: 2, confianza: 3, fundadores: 4, explica: 3 },
    summary:
      "Ya funciona (flash de app) → 4 beneficios con dedos y chips (Pro 6 meses, precio para siempre, WhatsApp, tu voz define) → por qué solo 15 (onboarding personal) → comenta FUNDADOR.",
    detailed: true,
  },
  {
    id: 5,
    title: "POV: son las 7 am y ya sabes qué cobrar",
    pillar: "P3",
    objective: "Demo del Centro de Prioridades sin parecer demo. Tu video de práctica (casi sin cara).",
    problem: "El espectador no imagina cómo se ve “tener el control”; esto se lo hace sentir.",
    hook: "📱 dedo abriendo la app + “POV: tu negocio te dice qué hacer HOY” + sonido de notificación",
    cta: "Así se siente tener el control · link en bio, gratis",
    durationSec: 22,
    effortMin: 20,
    emotions: ["deseo", "calma"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 4, confianza: 1, fundadores: 2, explica: 3 },
    summary:
      "Voz en off serena sobre pantalla real: prioridades del día con 3 zooms → “no lo pensé yo, la app lo calculó” → tu cara 1.5 s al final (la sorpresa que humaniza).",
    detailed: true,
  },
  {
    id: 6,
    title: "Errores que descubrí llevando mi propio dinero",
    pillar: "P4",
    objective: "Autoridad por vulnerabilidad: el creador también se equivoca.",
    hook: "“Perdí plata 6 MESES sin darme cuenta” + gesto de dolor",
    cta: "Guárdalo para no olvidarlo (save)",
    durationSec: 35,
    effortMin: 25,
    emotions: ["sorpresa", "gratitud por el consejo"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 2, confianza: 3, fundadores: 2, explica: 2 },
    summary:
      "Creía que lo vendido era lo ganado → no restaba compras ni gastos hormiga → al calcular bien, la “ganancia” era la mitad → pantalla de ganancia real → “importa cuánto te QUEDA”.",
  },
  {
    id: 7,
    title: "Semana N construyendo Zentro (serie)",
    pillar: "P2",
    objective: "Inaugurar la serie semanal que crea seguidores (no solo views). Formato repetible.",
    hook: "“Estoy construyendo una app en público. Semana 1: 3 cosas pasaron.” + flash de código",
    cta: "¿Qué le agregarías tú? Los mejores comentarios entran al roadmap",
    durationSec: 40,
    effortMin: 30,
    emotions: ["curiosidad de insider", "pertenencia"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 3, fundadores: 2, explica: 2 },
    summary:
      "Estructura fija semanal: (1) qué construí [pantalla], (2) qué se rompió / aprendí [honestidad], (3) qué viene [teaser]. Contador “SEMANA N” grande, misma posición siempre.",
  },
  {
    id: 8,
    title: "Le pregunté a una revendedora cuánto le deben",
    pillar: "P1",
    objective: "Dolor validado por un tercero: más creíble que tú solo.",
    hook: "Texto: “Le deben $X y no lo sabía” + su reacción (“¿¡TANTO!?”)",
    cta: "¿Tú sí sabes cuánto te deben? Número exacto. Te leo 👇",
    durationSec: 30,
    effortMin: 60,
    emotions: ["shock por el número", "identificación"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 4, facilidad: 1, confianza: 3, fundadores: 3, explica: 1 },
    summary:
      "Entrevista casual: ella calcula en voz alta, se ríe nerviosa, el número real la sorprende → “no es raro: es el estándar” → CTA. Número final GIGANTE en verde.",
    requiresReal: "Necesita una persona real con permiso (no actuar).",
  },
  {
    id: 9,
    title: "Hice que la app celebre cuando cobras",
    pillar: "P2",
    objective: "Decisión de producto con alma: build in public que demuestra cuidado.",
    hook: "“Programé un botón que solo existe para hacerte sentir bien.”",
    cta: "¿Qué momento de tu negocio merece celebrarse? Lo programo",
    durationSec: 25,
    effortMin: 20,
    emotions: ["ternura/deleite", "deseo"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 3, fundadores: 1, explica: 3 },
    summary:
      "Cobrar una deuda vieja se siente increíble y ninguna app lo celebra → pantalla: “Cobraste $X 🎉 ¡Factura saldada!” + cha-ching → “los números también son emociones”.",
  },
  {
    id: 10,
    title: "Excel vs Zentro: la misma venta",
    pillar: "P3",
    objective: "Comparación honesta sin nombrar competidores: el rival es el statu quo.",
    hook: "Pantalla dividida: “Registrar una venta: ANTES vs AHORA” + timer corriendo",
    cta: "3 taps. Link en bio, gratis",
    durationSec: 30,
    effortMin: 40,
    emotions: ["pereza reconocida", "asombro por el contraste"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 2, confianza: 2, fundadores: 2, explica: 3 },
    summary:
      "Lado A (hastío actuado): laptop, archivo, fila 847, fórmula rota. Lado B: botón +, monto, listo (cronometrado). “No odias los números. Odias la fricción.”",
  },
  {
    id: 11,
    title: "Un usuario me pidió esto el lunes. Hoy ya existe",
    pillar: "P5",
    objective: "LA prueba social del modelo fundador: pides → yo construyo.",
    hook: "Screenshot del pedido (nombre tapado) + “me pidió esto el LUNES”",
    cta: "¿Qué le falta a Zentro para servirte a TI? Pídemelo. Va en serio",
    durationSec: 28,
    effortMin: 25,
    emotions: ["asombro", "ganas de pedir algo"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 4, fundadores: 3, explica: 2 },
    summary:
      "Pedido real → “su voz ES el roadmap” → la feature funcionando → línea de tiempo LUN→MAR→MIÉ animada → CTA.",
    requiresReal: "Necesita un caso real de feedback → feature (no inventarlo jamás).",
  },
  {
    id: 12,
    title: "No busco que me compres",
    pillar: "P4",
    objective: "Desarmar el cinismo: decir en voz alta lo que todos piensan de los anuncios.",
    hook: "Muy serio: “No quiero que me compres nada. En serio.” (sin música los primeros 5 s)",
    cta: "Si esto te suena honesto, ya sabes dónde está el link",
    durationSec: 30,
    effortMin: 20,
    emotions: ["desconcierto", "respeto → confianza"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 4, fundadores: 3, explica: 2 },
    summary:
      "Está en pruebas: cobrarte hoy sería venderte algo a medio pulir → necesito 15 que digan la verdad → trato justo (gratis + soporte ↔ feedback) → precio de fundador cuando cobre. Plano fijo, calma a propósito.",
  },

  // ——— P1 · Dolor / espejo (13-24) ———
  {
    id: 13,
    title: "El cliente que “ahorita te pago”",
    pillar: "P1",
    objective: "Humor de identificación con los morosos.",
    hook: "Imitando al cliente: “‘ahorita te pago’ — ahorita lleva 47 días”",
    cta: "Etiqueta a quien tiene un “ahorita” pendiente",
    durationSec: 20,
    effortMin: 20,
    emotions: ["risa cómplice"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 2, fundadores: 2, explica: 2 },
    summary: "Desfile de frases típicas de morosos (chips) → “que la app los persiga por ti” → flash recordatorio.",
  },
  {
    id: 14,
    title: "¿Cuánto ganaste ESTE mes? (número exacto)",
    pillar: "P1",
    objective: "El reto imposible que expone el problema.",
    hook: "Pregunta directa + timer de 5 s corriendo en pantalla",
    cta: "Comenta SÍ o NO, honesto",
    durationSec: 18,
    effortMin: 15,
    emotions: ["incomodidad productiva"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 4, confianza: 2, fundadores: 2, explica: 2 },
    summary: "Silencio incómodo de 5 s → “si dudaste, tu negocio vive en tu cabeza” → pantalla de ganancia real.",
  },
  {
    id: 15,
    title: "Vender no es lo difícil",
    pillar: "P1",
    objective: "Reencuadrar el dolor: lo difícil es cobrar, ordenar y saber si ganas.",
    hook: "Texto: “vender es lo FÁCIL”",
    cta: "Link en bio",
    durationSec: 25,
    effortMin: 20,
    emotions: ["validación"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 2, fundadores: 2, explica: 2 },
    summary: "Cobrar, ordenar, saber si ganas — cada uno con inserto de 1 s → Zentro hace las 3.",
  },
  {
    id: 16,
    title: "El cuaderno de fiados de tu mamá",
    pillar: "P1",
    objective: "Nostalgia + dolor, con respeto (homenaje, no burla).",
    hook: "Cuaderno viejo real a cámara",
    cta: "¿Tu familia tuvo uno? Cuéntame",
    durationSec: 30,
    effortMin: 25,
    emotions: ["ternura", "reconocimiento"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 3, fundadores: 2, explica: 2 },
    summary: "“Funcionó 20 años... hasta que se mojó/perdió” → “esto es el cuaderno, pero no se pierde y suma solo”.",
  },
  {
    id: 17,
    title: "3 señales de que tu negocio te maneja a ti",
    pillar: "P1",
    objective: "Autodiagnóstico en formato lista.",
    hook: "“Señal 1: apagas incendios, no decides.”",
    cta: "¿Cuántas tienes? 1, 2 o 3",
    durationSec: 30,
    effortMin: 20,
    emotions: ["autodiagnóstico"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 2, fundadores: 2, explica: 2 },
    summary: "3 señales con corte por ítem → la app que invierte el control.",
  },
  {
    id: 18,
    title: "La plata que se pierde en el “después lo anoto”",
    pillar: "P1",
    objective: "Micro-dolor universal: la venta sin registrar.",
    hook: "Actuado: vendes, te distraes, no anotaste",
    cta: "Save (guárdalo)",
    durationSec: 22,
    effortMin: 20,
    emotions: ["culpa ligera → alivio"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 2, fundadores: 2, explica: 3 },
    summary: "“3 ventas sin anotar al mes = $X al año” (cifra creciendo) → botón “+” 3 taps.",
  },
  {
    id: 19,
    title: "Fiar o no fiar",
    pillar: "P1",
    objective: "Debate de comentarios garantizado.",
    hook: "“Fiar te consigue clientes... y te quiebra.”",
    cta: "¿Tú fías? 🔥 debate abajo",
    durationSec: 25,
    effortMin: 20,
    emotions: ["polémica sana"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 4, facilidad: 3, confianza: 2, fundadores: 2, explica: 2 },
    summary: "Las 2 posturas → “fía, pero con sistema: fecha + recordatorio automático”.",
  },
  {
    id: 20,
    title: "Tu Excel tiene una fórmula rota ahora mismo",
    pillar: "P1",
    objective: "Miedo específico y jocoso del usuario de Excel.",
    hook: "Susurro conspirador a cámara",
    cta: "Link en bio",
    durationSec: 20,
    effortMin: 15,
    emotions: ["paranoia jocosa"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 4, confianza: 2, fundadores: 2, explica: 2 },
    summary: "“Y no sabes cuál... hasta que decides con un número falso” → app que calcula sin fórmulas.",
  },
  {
    id: 21,
    title: "Por qué tu negocio “va bien” pero no hay plata",
    pillar: "P1",
    objective: "Resolver el misterio central del ICP.",
    hook: "La paradoja dicha de frente",
    cta: "Save + comenta cuál es la tuya",
    durationSec: 35,
    effortMin: 25,
    emotions: ["revelación"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 3, fundadores: 2, explica: 3 },
    summary: "3 causas (fías mucho, gastos hormiga, compras sin control) → verlas juntas en pantalla.",
  },
  {
    id: 22,
    title: "Lo que tu contador no te dice",
    pillar: "P1",
    objective: "Autoridad: separar contabilidad fiscal de decisiones diarias.",
    hook: "“Tu contador te dice cuánto pagar de impuestos. No cuánto estás GANANDO.”",
    cta: "Link en bio",
    durationSec: 30,
    effortMin: 20,
    emotions: ["sorpresa"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 3, fundadores: 2, explica: 2 },
    summary: "Contabilidad ≠ decisiones diarias → Zentro es lo segundo.",
  },
  {
    id: 23,
    title: "El mensaje que NO te atreves a mandar",
    pillar: "P1",
    objective: "Dolor de cobrar v2, en formato pantalla.",
    hook: "Chat con mensaje de cobro escrito y borrado 3 veces",
    cta: "Comenta COBRA",
    durationSec: 20,
    effortMin: 15,
    emotions: ["vergüenza compartida"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 2, fundadores: 3, explica: 2 },
    summary: "Grabación de notas escribiendo/borrando → “yo tampoco podía. Por eso lo automaticé”.",
  },
  {
    id: 24,
    title: "Cerraste el mes. ¿Y ahora qué?",
    pillar: "P1",
    objective: "Ritual de fin de mes (timing estacional).",
    hook: "“31 de julio: caos de papelitos” vs resumen en 1 pantalla",
    cta: "Prepárate para agosto, link en bio",
    durationSec: 25,
    effortMin: 20,
    emotions: ["anticipación"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 2, fundadores: 2, explica: 3 },
    summary: "Papelitos vs resumen del mes en Zentro.",
    timing: "Publicar el 30-31 de julio.",
  },

  // ——— P2 · Construyendo Zentro en público (25-33) ———
  {
    id: 25,
    title: "Semana N construyendo Zentro (episodios)",
    pillar: "P2",
    objective: "La serie continua del #7: un episodio cada semana.",
    hook: "“Semana N: esto pasó.”",
    cta: "¿Qué le agregarías tú?",
    durationSec: 40,
    effortMin: 30,
    emotions: ["pertenencia"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 3, fundadores: 2, explica: 2 },
    summary: "Mismo formato del #7: construí / se rompió / viene. Este brief vale por 8+ videos.",
  },
  {
    id: 26,
    title: "Programé hasta las 2 am por este botón",
    pillar: "P2",
    objective: "Sacrificio visible con propósito.",
    hook: "Ojeras + timelapse del editor",
    cta: "Sígueme",
    durationSec: 25,
    effortMin: 25,
    emotions: ["admiración"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 3, fundadores: 2, explica: 2 },
    summary: "Qué era el botón y POR QUÉ importaba para un usuario.",
  },
  {
    id: 27,
    title: "Lo que costaría Zentro si lo hiciera una empresa",
    pillar: "P2",
    objective: "Anclar el valor percibido.",
    hook: "“CRM + finanzas + cobrador = $80/mes en 3 apps” (desglose en chips)",
    cta: "Comenta FUNDADOR",
    durationSec: 30,
    effortMin: 25,
    emotions: ["oportunidad"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 2, fundadores: 3, explica: 3 },
    summary: "Desglose de precios de mercado → “lo estoy regalando a 15 personas, y esta es la razón”.",
  },
  {
    id: 28,
    title: "Rompí la app un viernes a las 6 pm",
    pillar: "P2",
    objective: "Historia de bug con honestidad: la transparencia más rentable.",
    hook: "“Rompí mi propia app. Un viernes. A las 6.”",
    cta: "Sígueme para el próximo incendio",
    durationSec: 35,
    effortMin: 25,
    emotions: ["humor", "respeto"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 4, fundadores: 2, explica: 2 },
    summary: "El error, el pánico, el fix, la lección → “por esto la fase de pruebas existe y los fundadores valen oro”.",
  },
  {
    id: 29,
    title: "Así se ve mi “oficina”",
    pillar: "P2",
    objective: "Behind the scenes que humaniza.",
    hook: "Tour de 15 s del escritorio real",
    cta: "¿Desde dónde trabajas tú?",
    durationSec: 20,
    effortMin: 15,
    emotions: ["cercanía"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 4, confianza: 3, fundadores: 1, explica: 1 },
    summary: "“Desde aquí sale una app que usan negocios reales. No hace falta más.”",
  },
  {
    id: 30,
    title: "Por qué la app habla como tú (no como Silicon Valley)",
    pillar: "P2",
    objective: "Filosofía de producto: identidad del español.",
    hook: "“Las apps de negocio hablan inglés de Silicon Valley. Tu negocio habla como tú.”",
    cta: "¿Qué palabra odias de las apps gringas?",
    durationSec: 30,
    effortMin: 20,
    emotions: ["identidad"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 3, fundadores: 2, explica: 2 },
    summary: "Ejemplos de textos reales de la app en español claro.",
  },
  {
    id: 31,
    title: "Le puse un botón de + gigante y esta es la razón",
    pillar: "P2",
    objective: "Diseño explicado: fricción mata hábito.",
    hook: "Barra móvil en pantalla",
    cta: "Link en bio",
    durationSec: 25,
    effortMin: 20,
    emotions: ["insight"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 3, fundadores: 1, explica: 3 },
    summary: "“Una venta se registra en 3 taps o no se registra nunca.”",
  },
  {
    id: 32,
    title: "Cuánto llevo gastado construyendo Zentro",
    pillar: "P2",
    objective: "Transparencia radical de números.",
    hook: "Desglose real (dominio, infra, tiempo) en chips",
    cta: "Sígueme: números reales cada mes",
    durationSec: 35,
    effortMin: 25,
    emotions: ["confianza"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 4, fundadores: 2, explica: 2 },
    summary: "Gastos reales → “y por qué aún así no te cobro todavía”.",
  },
  {
    id: 33,
    title: "Mi app se instala sin App Store",
    pillar: "P2",
    objective: "La PWA como magia accesible.",
    hook: "Instalar desde el navegador, ícono en el home",
    cta: "Pruébalo, link en bio",
    durationSec: 25,
    effortMin: 15,
    emotions: ["sorpresa técnica"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 4, confianza: 2, fundadores: 2, explica: 3 },
    summary: "“Sin descargas de 200 MB, sin actualizaciones” → pantalla de /guide.",
  },

  // ——— P3 · Demos / momento dinero (34-42) ———
  {
    id: 34,
    title: "Registra una venta en 3 segundos",
    pillar: "P3",
    objective: "Micro-tutorial cronometrado, el más corto de grabar.",
    hook: "Timer en pantalla, sin intro",
    cta: "Gratis, link en bio",
    durationSec: 15,
    effortMin: 10,
    emotions: ["eficiencia"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 4, confianza: 2, fundadores: 2, explica: 4 },
    summary: "Botón + → monto → listo, cronometrado.",
  },
  {
    id: 35,
    title: "Cómo saber quién te debe (en 1 pantalla)",
    pillar: "P3",
    objective: "Tutorial de cobranza.",
    hook: "“¿Quién te debe? Una pantalla.”",
    cta: "Comenta ORDEN",
    durationSec: 25,
    effortMin: 15,
    emotions: ["control"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 4, confianza: 2, fundadores: 3, explica: 4 },
    summary: "Lista con montos → ordenar por antigüedad → activar recordatorio.",
  },
  {
    id: 36,
    title: "El correo que le llega a tu cliente moroso",
    pillar: "P3",
    objective: "Mostrar la carta, no el arma: el recordatorio real.",
    hook: "El correo REAL línea por línea (con zoom)",
    cta: "Comenta COBRA",
    durationSec: 22,
    effortMin: 15,
    emotions: ["alivio"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 4, confianza: 3, fundadores: 3, explica: 4 },
    summary: "“Amable, con tu nombre, y funciona.”",
  },
  {
    id: 37,
    title: "Del caos a orden en 10 minutos",
    pillar: "P3",
    objective: "El onboarding como timelapse.",
    hook: "“Esto es lo que hacemos juntos en tu onboarding.”",
    cta: "Comenta FUNDADOR",
    durationSec: 40,
    effortMin: 30,
    emotions: ["posibilidad"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 3, fundadores: 3, explica: 4 },
    summary: "Importar clientes, 3 productos, 1 factura → dashboard vivo.",
  },
  {
    id: 38,
    title: "¿Ganancia o ilusión? El número verde",
    pillar: "P3",
    objective: "Demo de finanzas sin doble conteo.",
    hook: "“¿Estás ganando o solo estás vendiendo?”",
    cta: "Save",
    durationSec: 25,
    effortMin: 15,
    emotions: ["claridad"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 4, confianza: 2, fundadores: 2, explica: 4 },
    summary: "Ingresos − gastos − compras → “sin fórmulas”.",
  },
  {
    id: 39,
    title: "Zentro en tu bolsillo (celular, no laptop)",
    pillar: "P3",
    objective: "Demo móvil grabado en la calle/tienda.",
    hook: "Venta registrada desde el mostrador",
    cta: "Link en bio",
    durationSec: 20,
    effortMin: 25,
    emotions: ["movilidad"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 2, fundadores: 2, explica: 4 },
    summary: "“Tu negocio no pasa en un escritorio.”",
  },
  {
    id: 40,
    title: "Lo que ve tu cliente cuando le cobras con Zentro",
    pillar: "P3",
    objective: "POV del cliente: cerrar el loop de confianza.",
    hook: "El otro lado: recibe recordatorio → paga → “cobrado ✓”",
    cta: "Comenta COBRA",
    durationSec: 20,
    effortMin: 15,
    emotions: ["profesionalismo"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 4, confianza: 3, fundadores: 3, explica: 4 },
    summary: "El flujo completo visto desde el cliente.",
  },
  {
    id: 41,
    title: "SE LLENARON los 15 cupos",
    pillar: "P5",
    objective: "Escasez cumplida: prueba social máxima.",
    hook: "F5 con casillas llenas + “gracias”",
    cta: "Lista de espera, link en bio",
    durationSec: 20,
    effortMin: 15,
    emotions: ["FOMO real", "gratitud"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 3, facilidad: 4, confianza: 3, fundadores: 4, explica: 2 },
    summary: "“Ahora: lista de espera” → qué ganan los de la lista.",
    requiresReal: "Guardarlo para cuando el cupo 15 se llene de verdad.",
  },
  {
    id: 42,
    title: "Un día usando MI propia app",
    pillar: "P3",
    objective: "Dogfooding: coherencia visible.",
    hook: "“Si no la usara yo, no te la ofrecería.”",
    cta: "Sígueme",
    durationSec: 45,
    effortMin: 40,
    emotions: ["coherencia"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 2, confianza: 3, fundadores: 2, explica: 3 },
    summary: "Vlog: Zentro gestionando el propio proyecto Zentro (gastos de infra, tareas).",
  },

  // ——— P4 · Historias y aprendizajes (43-51) ———
  {
    id: 43,
    title: "Lo que aprendí del negocio de mi familia",
    pillar: "P4",
    objective: "Raíces (ajustar a la historia REAL; si no aplica, usar la de un conocido).",
    hook: "Storytelling de origen",
    cta: "¿De qué negocio vienes tú?",
    durationSec: 40,
    effortMin: 35,
    emotions: ["nostalgia"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 2, confianza: 4, fundadores: 2, explica: 1 },
    summary: "Esa experiencia está dentro de Zentro.",
  },
  {
    id: 44,
    title: "3 años pensando que “organizarme” era comprar otra agenda",
    pillar: "P4",
    objective: "Confesión con humor.",
    hook: "Agendas/apps acumuladas a cámara",
    cta: "¿Cuántas agendas tienes?",
    durationSec: 30,
    effortMin: 25,
    emotions: ["risa culpable"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 3, fundadores: 2, explica: 1 },
    summary: "“El problema no era la herramienta: era que ninguna DECIDÍA por mí.”",
  },
  {
    id: 45,
    title: "Me dijeron que estaba loco por regalar 6 meses",
    pillar: "P4",
    objective: "Convertir la objeción en contenido.",
    hook: "“Un amigo me dijo: ‘vas a perder plata’.”",
    cta: "Comenta FUNDADOR",
    durationSec: 25,
    effortMin: 20,
    emotions: ["convicción"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 4, fundadores: 3, explica: 2 },
    summary: "Tu lógica: 15 usuarios reales valen más que 15 pagos hoy.",
  },
  {
    id: 46,
    title: "Qué haría diferente si empezara mi negocio hoy",
    pillar: "P4",
    objective: "Consejo entre pares (no mentor de humo).",
    hook: "“3 cosas. La tercera nadie la hace.”",
    cta: "Save + comenta la tuya",
    durationSec: 35,
    effortMin: 25,
    emotions: ["mentoría entre pares"],
    funnel: "frio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 3, fundadores: 2, explica: 1 },
    summary: "Anotar TODO desde el día 1, separar plata personal, cobrar con sistema.",
  },
  {
    id: 47,
    title: "El día que un extraño confió en mi app",
    pillar: "P4",
    objective: "Hito emocional (grabar cuando pase).",
    hook: "“Hoy alguien que no conozco me confió su negocio.”",
    cta: "Sígueme",
    durationSec: 30,
    effortMin: 20,
    emotions: ["gratitud", "responsabilidad"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 4, fundadores: 2, explica: 1 },
    summary: "El primer registro orgánico: cómo se sintió.",
    requiresReal: "Esperar al primer registro orgánico real.",
  },
  {
    id: 48,
    title: "No soy una empresa. Soy una persona",
    pillar: "P4",
    objective: "Anti-corporativo: la cercanía como ventaja.",
    hook: "“Detrás de Zentro no hay oficina con futbolín: hay este escritorio.”",
    cta: "Mi WhatsApp responde, pruébame",
    durationSec: 25,
    effortMin: 20,
    emotions: ["humanidad"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 4, fundadores: 3, explica: 2 },
    summary: "Por qué eso es MEJOR para el usuario hoy (velocidad, cercanía).",
  },
  {
    id: 49,
    title: "Todo lo que me da miedo de esto",
    pillar: "P4",
    objective: "Vulnerabilidad estratégica.",
    hook: "“Esto es todo lo que me da miedo.” (pausa)",
    cta: "¿Qué te da miedo a ti de emprender?",
    durationSec: 35,
    effortMin: 25,
    emotions: ["valentía compartida"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 4, fundadores: 2, explica: 1 },
    summary: "Miedos honestos (que nadie la use, un bug feo) → “y lo hago igual, porque el problema es real”.",
  },
  {
    id: 50,
    title: "Mi North Star no son las descargas",
    pillar: "P4",
    objective: "Visión: métricas de verdad vs vanidad.",
    hook: "“Mido UNA cosa: cuánta plata cobran a tiempo mis usuarios.”",
    cta: "¿Cuál es TU número?",
    durationSec: 25,
    effortMin: 20,
    emotions: ["propósito"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 3, fundadores: 2, explica: 2 },
    summary: "Aplica a todo negocio: ¿cuál es tu métrica de verdad?",
  },
  {
    id: 51,
    title: "Respondiendo al comentario que me dolió",
    pillar: "P4",
    objective: "Respuesta en video a una crítica real.",
    hook: "El comentario en pantalla (“otra app más...”)",
    cta: "Pregúntame lo que sea",
    durationSec: 30,
    effortMin: 20,
    emotions: ["madurez"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 4, fundadores: 2, explica: 2 },
    summary: "Darle la razón en lo justo → tu diferencia sin defensividad.",
    requiresReal: "Usar un comentario real recibido.",
  },

  // ——— P5 · Comunidad y feedback (52-60) ———
  {
    id: 52,
    title: "Los usuarios pidieron, yo programé: ronda 1",
    pillar: "P5",
    objective: "Recap de mejoras con nombre de quien las pidió.",
    hook: "“Ustedes pidieron. Yo programé.”",
    cta: "Pide la tuya",
    durationSec: 30,
    effortMin: 25,
    emotions: ["reciprocidad"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 4, fundadores: 4, explica: 2 },
    summary: "3 mejoras con chips LUN pedido → JUE en producción. Repetible cada 2-3 semanas.",
    requiresReal: "Necesita feedback real (con permiso).",
  },
  {
    id: 53,
    title: "Configurando el negocio #N en vivo",
    pillar: "P5",
    objective: "El onboarding como contenido.",
    hook: "Timelapse de la sesión 1-a-1",
    cta: "Quedan X cupos",
    durationSec: 40,
    effortMin: 30,
    emotions: ["prueba social"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 2, confianza: 4, fundadores: 4, explica: 3 },
    summary: "La reacción del usuario al ver su dashboard.",
    requiresReal: "Con permiso del usuario fundador.",
  },
  {
    id: 54,
    title: "Le pregunté a mis usuarios qué odian de las apps",
    pillar: "P5",
    objective: "Investigación pública.",
    hook: "3 respuestas reales en chips",
    cta: "¿Tú qué odias?",
    durationSec: 30,
    effortMin: 25,
    emotions: ["escucha"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 4, fundadores: 3, explica: 2 },
    summary: "Cuáles va a resolver Zentro.",
    requiresReal: "Necesita respuestas reales de usuarios.",
  },
  {
    id: 55,
    title: "Reaccionando al primer feedback duro",
    pillar: "P5",
    objective: "Crítica bien recibida = confianza.",
    hook: "El feedback en pantalla → “tiene razón”",
    cta: "Dime qué más está mal, en serio",
    durationSec: 30,
    effortMin: 20,
    emotions: ["humildad"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 4, fundadores: 3, explica: 2 },
    summary: "El fix en vivo tras aceptar la crítica.",
    requiresReal: "Usar feedback real.",
  },
  {
    id: 56,
    title: "El primer cobro real hecho con Zentro",
    pillar: "P5",
    objective: "Hito North Star.",
    hook: "La cifra en verde + cha-ching",
    cta: "El tuyo puede ser el próximo",
    durationSec: 25,
    effortMin: 15,
    emotions: ["celebración"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 3, facilidad: 3, confianza: 4, fundadores: 3, explica: 2 },
    summary: "“Esta es la razón de todo” (datos censurados).",
    requiresReal: "Esperar al primer cobro real de un usuario.",
  },
  {
    id: 57,
    title: "Q&A: ¿mis datos están seguros? ¿y si cierras?",
    pillar: "P5",
    objective: "Objeciones de frente.",
    hook: "“Las 2 preguntas que más me hacen. Sin rodeos.”",
    cta: "Más preguntas abajo",
    durationSec: 35,
    effortMin: 25,
    emotions: ["seriedad"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 4, fundadores: 3, explica: 3 },
    summary: "Respuestas directas: cifrado, export de datos, compromiso.",
  },
  {
    id: 58,
    title: "Encuesta: ¿qué construyo primero?",
    pillar: "P5",
    objective: "Decisión delegada a la audiencia.",
    hook: "2 features candidatas en 5 s cada una",
    cta: "Vota A o B",
    durationSec: 20,
    effortMin: 15,
    emotions: ["agencia"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 4, confianza: 3, fundadores: 2, explica: 2 },
    summary: "El video siguiente anuncia el resultado (mini-serie de 2).",
  },
  {
    id: 59,
    title: "1 mes de Zentro en números públicos",
    pillar: "P5",
    objective: "Reporte mensual transparente (formato repetible).",
    hook: "“Números reales. Incluidos los feos.”",
    cta: "Sígueme para el reporte de agosto",
    durationSec: 35,
    effortMin: 30,
    emotions: ["transparencia"],
    funnel: "tibio",
    platforms: ALL,
    scores: { viral: 2, facilidad: 3, confianza: 4, fundadores: 2, explica: 2 },
    summary: "Usuarios, feedbacks, mejoras enviadas, lo que falló.",
    timing: "Fin de cada mes.",
  },
  {
    id: 60,
    title: "Gracias, primeros 15",
    pillar: "P5",
    objective: "Cierre de campaña con los negocios fundadores.",
    hook: "Collage de los negocios (con permiso)",
    cta: "Lista de espera",
    durationSec: 30,
    effortMin: 25,
    emotions: ["comunidad lograda"],
    funnel: "conversion",
    platforms: ALL,
    scores: { viral: 2, facilidad: 2, confianza: 4, fundadores: 4, explica: 1 },
    summary: "“Ellos están construyendo Zentro conmigo” → lista de espera abierta.",
    requiresReal: "Guardarlo para el cierre real del cupo.",
  },
];

export function getVideo(id: number): Video | undefined {
  return VIDEOS.find((v) => v.id === id);
}
